/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Consultas;

import Utils.TipoDato;
import java.awt.BorderLayout;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import servicios.BaseDeDatos.*;

/**
 * Formulario Swing para consultas multitabla completas.
 * Permite seleccionar una entidad en un JComboBox y muestra todos sus registros
 * en una tabla con soporte de ordenación.
 *
 * @author 1DAM
 */
public class ConsultaCompleta extends javax.swing.JFrame {

    private JTable tabla;
    private JScrollPane scrollPane;

    /**
     * Creates new form ConsultaCompleta
     */
    public ConsultaCompleta() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        configurarVentana();
        inicializarTabla();
        conectarYCargarDatos();
    }

    /** Establece la conexión con la BD y carga la tabla inicial; deshabilita el combo si la conexión falla. */
    private void conectarYCargarDatos() {
        if (GestionBaseDeDatos.vincularBDD()) {
            cargarTabla();
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "No se ha podido conectar con la base de datos.",
                    "Error de conexión",
                    JOptionPane.ERROR_MESSAGE
            );

            jComboBoxEleccion.setEnabled(false);
        }
    }

    /** Configura el título, la política de cierre y el listener que pide confirmación antes de cerrar. */
    private void configurarVentana() {
        setLocationRelativeTo(null);
        setTitle("Consultas completas");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                cerrarVentana();
            }
        });
    }

    /** Muestra un diálogo de confirmación y cierra la ventana solo si el usuario acepta. */
    private void cerrarVentana() {
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres cerrar la ventana de consultas?",
                "Cerrar consultas",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxEleccion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("NSimSun", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONSULTAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1140, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        jComboBoxEleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Matrícula", "Línea Matrícula", "Módulo", "Ciclo" }));
        jComboBoxEleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEleccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jComboBoxEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(339, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEleccionActionPerformed
        if (tabla != null) {
            cargarTabla();
        }
    }//GEN-LAST:event_jComboBoxEleccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaCompleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ConsultaCompleta().setVisible(true);
        });
    }

    /** Crea la JTable con scroll dentro del jPanel1 y configura el modo de redimensionado y ordenación. */
    private void inicializarTabla() {
        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());

        tabla = new JTable();
        tabla.setRowHeight(24);
        tabla.setAutoCreateRowSorter(true);
        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        scrollPane = new JScrollPane(tabla);

        jPanel1.add(scrollPane, BorderLayout.CENTER);

        jPanel1.revalidate();
        jPanel1.repaint();
    }

    /**
     * Devuelve la sentencia SQL de selección completa para el tipo de entidad indicado.
     * @param tipo Entidad de la que se quiere obtener todos los registros.
     * @return Sentencia SQL lista para ejecutar, o {@code null} si el tipo no está soportado.
     */
    private String obtenerSQL(TipoDato tipo) {
        return switch (tipo) {
            case ALUMNO ->
                ConsultasSQL.SELECT_ALUMNO_TODOS[0];
            case MODULO ->
                ConsultasSQL.SELECT_MODULO_TODOS[0];
            case CICLO ->
                ConsultasSQL.SELECT_CICLO_TODOS[0];
            case MATRICULA ->
                ConsultasSQL.SELECT_MATRICULA_TODOS[0];
            case LINEA_MATRICULA ->
                ConsultasSQL.SELECT_LINEA_MATRICULA_TODOS[0];
            default ->
                null;
        };
    }

    /** Ejecuta la consulta SQL correspondiente a la entidad seleccionada en el combo y actualiza la tabla. */
    private void cargarTabla() {
    try {
        TipoDato tipo = obtenerTipoSeleccionado();
        String sql = obtenerSQL(tipo);

        if (sql == null || sql.isBlank()) {
            JOptionPane.showMessageDialog(this, "No hay consulta SQL definida.");
            return;
        }

        DefaultTableModel modelo = GestionBaseDeDatos.obtenerTableModel(sql, new String[0]);

        tabla.setModel(modelo);

        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
        tabla.setRowSorter(sorter);

        tabla.setRowHeight(24);
        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

        scrollPane.setViewportView(tabla);

        tabla.revalidate();
        tabla.repaint();

        scrollPane.revalidate();
        scrollPane.repaint();

        jPanel1.revalidate();
        jPanel1.repaint();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(
                this,
                "Error cargando datos:\n" + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );

        e.printStackTrace();
    }
}

    /**
     * Convierte el texto seleccionado en el JComboBox al {@link TipoDato} correspondiente.
     * @return TipoDato que representa la entidad elegida.
     */
    private TipoDato obtenerTipoSeleccionado() {
        String seleccion = jComboBoxEleccion.getSelectedItem().toString();

        return switch (seleccion) {
            case "Alumno" ->
                TipoDato.ALUMNO;
            case "Módulo" ->
                TipoDato.MODULO;
            case "Ciclo" ->
                TipoDato.CICLO;
            case "Matrícula" ->
                TipoDato.MATRICULA;
            case "Línea Matrícula" ->
                TipoDato.LINEA_MATRICULA;
            default ->
                throw new IllegalArgumentException("Tipo no válido: " + seleccion);
        };
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxEleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
