/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Consultas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import servicios.BaseDeDatos.ConsultasEjercicios;
import servicios.BaseDeDatos.GestionBaseDeDatos;

/**
 * Formulario Swing para ejecutar los nueve ejercicios SQL predefinidos.
 * Permite seleccionar un ejercicio, muestra su descripción y, al pulsar Actualizar,
 * solicita los parámetros necesarios y presenta el resultado en una tabla.
 *
 * @author 1DAM
 */
public class Ejercicios extends javax.swing.JFrame {

    private final String[] descripciones = {
        "Ejercicio 1: Muestra todos los ciclos formativos junto con sus módulos y las horas de cada módulo. Sirve para ver la estructura completa de ciclos y módulos.",
        "Ejercicio 2: Muestra los módulos de un determinado nivel y curso, indicando el número de alumnos matriculados en cada módulo. Requiere introducir el nivel y el curso.",
        "Ejercicio 3: Muestra los alumnos matriculados en un año académico concreto junto con los módulos en los que están matriculados. Requiere introducir el año académico.",
        "Ejercicio 4: Muestra los alumnos, su fecha de nacimiento y sus calificaciones en un ciclo, curso y año académico concretos. Requiere introducir denominación del ciclo, curso y año académico.",
        "Ejercicio 5: Calcula el importe total generado por cada ciclo y año académico, agrupando por ciclo, familia profesional, nivel y año académico.",
        "Ejercicio 6: Muestra el total de créditos ECTS y horas matriculadas por cada alumno en cada año académico.",
        "Ejercicio 7: Muestra los alumnos que todavía no tienen primera calificación en algún módulo.",
        "Ejercicio 8: Muestra los módulos que tienen más de tres alumnos repetidores. Sirve para detectar módulos con alta repetición.",
        "Ejercicio 9: Muestra los alumnos que no tienen matrícula o cuya matrícula está anulada."
    };

    /**
     * Creates new form Ejercicios
     */
    public Ejercicios() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        configurarVentana();
        actualizarDescripcion();

        if (!GestionBaseDeDatos.vincularBDD()) {
            JOptionPane.showMessageDialog(
                    this,
                    "No se ha podido conectar con la base de datos.",
                    "Error de conexión",
                    JOptionPane.ERROR_MESSAGE
            );

            jButtonActualizar.setEnabled(false);
        }
    }

    /** Configura el título, el cierre con confirmación, el comportamiento de la tabla y el área de descripción. */
    private void configurarVentana() {
        setLocationRelativeTo(null);
        setTitle("Ejercicios SQL");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                cerrarVentana();
            }
        });

        jTable1.setRowHeight(24);
        jTable1.setAutoCreateRowSorter(true);
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);

        jTextAreaDescripcion.setEditable(false);
        jTextAreaDescripcion.setLineWrap(true);
        jTextAreaDescripcion.setWrapStyleWord(true);
    }

    /** Muestra un diálogo de confirmación y cierra la ventana solo si el usuario acepta. */
    private void cerrarVentana() {
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres cerrar la ventana de ejercicios?",
                "Cerrar ejercicios",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxEleccion = new javax.swing.JComboBox<>();
        jButtonActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDescripcion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxEleccion.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxEleccion.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxEleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ejercicio 1", "Ejercicio 2", "Ejercicio 3", "Ejercicio 4", "Ejercicio 5", "Ejercicio 6", "Ejercicio 7", "Ejercicio 8", "Ejercicio 9" }));
        jComboBoxEleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEleccionActionPerformed(evt);
            }
        });

        jButtonActualizar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonActualizar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("NSimSun", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EJERCICIOS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTextAreaDescripcion.setEditable(false);
        jTextAreaDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaDescripcion.setColumns(20);
        jTextAreaDescripcion.setFont(new java.awt.Font("NSimSun", 0, 14)); // NOI18N
        jTextAreaDescripcion.setForeground(new java.awt.Color(0, 0, 0));
        jTextAreaDescripcion.setLineWrap(true);
        jTextAreaDescripcion.setRows(5);
        jTextAreaDescripcion.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextAreaDescripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonActualizar))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonActualizar)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxEleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEleccionActionPerformed
        actualizarDescripcion();

    }//GEN-LAST:event_jComboBoxEleccionActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        cargarTabla();
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Ejercicios().setVisible(true);
        });
    }

    /** Obtiene la SQL y los parámetros del ejercicio seleccionado, ejecuta la consulta y muestra el resultado en la tabla. */
    private void cargarTabla() {
        int opcion = jComboBoxEleccion.getSelectedIndex() + 1;

        String sql = obtenerSQL(opcion);

        if (sql == null || sql.isBlank()) {
            JOptionPane.showMessageDialog(this, "No hay consulta SQL definida.");
            return;
        }

        String[] parametros = obtenerParametros(opcion);

        if (parametros == null) {
            return;
        }

        DefaultTableModel modelo = GestionBaseDeDatos.obtenerTableModel(sql, parametros);

        jTable1.setModel(modelo);
        jTable1.setRowHeight(24);
        jTable1.setAutoCreateRowSorter(true);
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);

        jScrollPane1.setViewportView(jTable1);

        jTable1.revalidate();
        jTable1.repaint();
        jScrollPane1.revalidate();
        jScrollPane1.repaint();
    }

    /**
     * Devuelve la sentencia SQL del ejercicio indicado, obtenida de {@link ConsultasEjercicios}.
     * @param opcion Número de ejercicio (1-9).
     * @return Sentencia SQL, o {@code null} si el número no tiene ejercicio definido.
     */
    private String obtenerSQL(int opcion) {
        return switch (opcion) {
            case 1 ->
                ConsultasEjercicios.datosConsulta1[0];
            case 2 ->
                ConsultasEjercicios.datosConsulta2[0];
            case 3 ->
                ConsultasEjercicios.datosConsulta3[0];
            case 4 ->
                ConsultasEjercicios.datosConsulta4[0];
            case 5 ->
                ConsultasEjercicios.datosConsulta5[0];
            case 6 ->
                ConsultasEjercicios.datosConsulta6[0];
            case 7 ->
                ConsultasEjercicios.datosConsulta7[0];
            case 8 ->
                ConsultasEjercicios.datosConsulta8[0];
            case 9 ->
                ConsultasEjercicios.datosConsulta9[0];
            default ->
                null;
        };
    }

    /**
     * Solicita al usuario los parámetros necesarios para el ejercicio indicado.
     * @param opcion Número de ejercicio.
     * @return Array de parámetros, array vacío si el ejercicio no requiere ninguno, o {@code null} si el usuario cancela.
     */
    private String[] obtenerParametros(int opcion) {
        return switch (opcion) {
            case 2 ->
                pedirParametrosEjercicio2();
            case 3 ->
                pedirParametrosEjercicio3();
            case 4 ->
                pedirParametrosEjercicio4();
            default ->
                new String[0];
        };
    }

    /** Solicita nivel y curso mediante diálogos y los devuelve como array; devuelve {@code null} si el usuario cancela. */
    private String[] pedirParametrosEjercicio2() {
        String nivel = JOptionPane.showInputDialog(this, "Introduce nivel");

        if (nivel == null || nivel.isBlank()) {
            return null;
        }

        String curso = JOptionPane.showInputDialog(this, "Introduce curso");

        if (curso == null || curso.isBlank()) {
            return null;
        }

        return new String[]{nivel, curso};
    }

    /** Solicita el año académico mediante un diálogo y lo devuelve como array; devuelve {@code null} si el usuario cancela. */
    private String[] pedirParametrosEjercicio3() {
        String anioAcademico = JOptionPane.showInputDialog(this, "Introduce año académico");

        if (anioAcademico == null || anioAcademico.isBlank()) {
            return null;
        }

        return new String[]{anioAcademico};
    }

    /** Solicita denominación del ciclo, curso y año académico; devuelve {@code null} si el usuario cancela en cualquier paso. */
    private String[] pedirParametrosEjercicio4() {
        String denominacion = JOptionPane.showInputDialog(this, "Introduce denominación del ciclo");

        if (denominacion == null || denominacion.isBlank()) {
            return null;
        }

        String curso = JOptionPane.showInputDialog(this, "Introduce curso");

        if (curso == null || curso.isBlank()) {
            return null;
        }

        String anioAcademico = JOptionPane.showInputDialog(this, "Introduce año académico");

        if (anioAcademico == null || anioAcademico.isBlank()) {
            return null;
        }

        return new String[]{denominacion, curso, anioAcademico};
    }

    /** Muestra en el área de texto la descripción del ejercicio seleccionado en el combo. */
    private void actualizarDescripcion() {
        int indice = jComboBoxEleccion.getSelectedIndex();

        if (indice >= 0 && indice < descripciones.length) {
            jTextAreaDescripcion.setText(descripciones[indice]);
        } else {
            jTextAreaDescripcion.setText("");
        }
    }
    //No
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JComboBox<String> jComboBoxEleccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaDescripcion;
    // End of variables declaration//GEN-END:variables
}
