/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Consultas;

import javax.swing.JOptionPane;

/**
 * Menú de selección del módulo de consultas.
 * Permite navegar a las consultas unitabla, multitabla o a los ejercicios SQL.
 *
 * @author Rich
 */
public class SeleccionConsultas extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionConsultas
     */
    public SeleccionConsultas() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        configurarVentana();
    }

    /** Configura el título, la operación de cierre y el listener que pide confirmación al cerrar. */
    private void configurarVentana() {
        setLocationRelativeTo(null);
        setTitle("Menú de consultas");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                cerrarVentana();
            }
        });
    }

    /** Muestra un diálogo de confirmación y cierra la ventana solo si el usuario acepta. */
    private void cerrarVentana() {
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres cerrar el menú de consultas?",
                "Cerrar consultas",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonUniTabla = new javax.swing.JButton();
        jButtonMultitabla = new javax.swing.JButton();
        jButtonEjercicios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("NSimSun", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU CONSULTAS");

        jButtonUniTabla.setText("UNITABLA");
        jButtonUniTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUniTablaActionPerformed(evt);
            }
        });

        jButtonMultitabla.setText("MULTITABLA");
        jButtonMultitabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultitablaActionPerformed(evt);
            }
        });

        jButtonEjercicios.setText("EJERCICIOS");
        jButtonEjercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEjerciciosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(490, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEjercicios)
                            .addComponent(jButtonUniTabla))
                        .addGap(585, 585, 585))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(454, 454, 454))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(618, Short.MAX_VALUE)
                    .addComponent(jButtonMultitabla)
                    .addGap(581, 581, 581)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(156, 156, 156)
                .addComponent(jButtonUniTabla)
                .addGap(18, 18, 18)
                .addComponent(jButtonEjercicios)
                .addContainerGap(406, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(203, 203, 203)
                    .addComponent(jButtonMultitabla)
                    .addContainerGap(493, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMultitablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultitablaActionPerformed
        ConsultaCompleta cc = new ConsultaCompleta();
        cc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonMultitablaActionPerformed

    private void jButtonUniTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUniTablaActionPerformed
        ConsultaFila cf = new ConsultaFila();
        cf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonUniTablaActionPerformed

    private void jButtonEjerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEjerciciosActionPerformed
        Ejercicios ejercicios = new Ejercicios();
        ejercicios.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonEjerciciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SeleccionConsultas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEjercicios;
    private javax.swing.JButton jButtonMultitabla;
    private javax.swing.JButton jButtonUniTabla;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
