/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Eliminar;

import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import servicios.BaseDeDatos.GestionBaseDeDatos;
import java.awt.Dimension;

/**
 * Formulario Swing para eliminar un alumno de la base de datos.
 * Busca alumnos por teléfono y correo, los muestra en una tabla y, tras
 * confirmar los datos, borra el alumno junto con sus matrículas y líneas de matrícula.
 *
 * @author Rich
 */
public class ElimarAlumno extends javax.swing.JFrame {

    /**
     * Creates new form FormularioAlumno
     */
    public ElimarAlumno() {
        initComponents();
        configurarVentana();
        configurarTablaVacia();
    }

    /** Configura título, textos de etiquetas, tamaño de campos y el listener de selección de la tabla. */
    private void configurarVentana() {
        setLocationRelativeTo(null);
        setTitle("Eliminar alumno");
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonEliminar.setText("Eliminar alumno");
        jButton1.setText("Actualizar");

        jLabel1.setText("Teléfono:");
        jLabel3.setText("Correo:");
        jLabelTitulo.setText("ELIMINAR ALUMNADO");
        jLabelEliminar.setText("Elimina el alumno, sus matrículas y sus líneas de matrícula.");
        jLabel2.setText("Introduce teléfono y correo, pulsa Actualizar, selecciona el alumno y elimínalo.");

        jTextField1.setText("");
        jTextField2.setText("");

        Dimension tamañoCampos = new Dimension(220, 25);

        jTextField1.setColumns(20);
        jTextField1.setPreferredSize(tamañoCampos);
        jTextField1.setMinimumSize(tamañoCampos);

        jTextField2.setColumns(25);
        jTextField2.setPreferredSize(tamañoCampos);
        jTextField2.setMinimumSize(tamañoCampos);

        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                cargarDatosAlumnoSeleccionado();
            }
        });

        pack();
    }

    /** Establece en la tabla un modelo vacío con las columnas del alumno y celdas no editables. */
    private void configurarTablaVacia() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{"Código", "Nombre", "Fecha nacimiento", "Domicilio", "Teléfono", "Correo"},
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        jTable1.setModel(modelo);
    }

    /** Busca en la BD el alumno que coincide con el teléfono y correo introducidos y muestra el resultado en la tabla. */
    private void buscarAlumnoSeguro() {
        String telefono = jTextField1.getText().trim();
        String correo = jTextField2.getText().trim();

        if (telefono.isEmpty() || correo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes introducir teléfono y correo.");
            configurarTablaVacia();
            return;
        }

        DefaultTableModel modelo = GestionBaseDeDatos.obtenerAlumnoPorTelefonoYCorreo(telefono, correo);
        jTable1.setModel(modelo);

        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No se ha encontrado ningún alumno con ese teléfono y correo.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEliminar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelEliminar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("ELIMINAR ALUMNADO");

        jLabelEliminar.setText("Elimina el alumno, su matricula y su linea matricula");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setText("Telefono");

        jLabel2.setText("Compruebe que el alumno seleccionado es el correcto");

        jLabel3.setText("Correo");

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(236, 236, 236)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(538, 538, 538)
                                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(42, 42, 42)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(42, 42, 42)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(321, 321, 321)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEliminar)
                        .addGap(22, 22, 22)))
                .addContainerGap(403, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(567, 567, 567)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEliminar)
                    .addComponent(jLabelEliminar))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        eliminarAlumnoSeleccionado();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        buscarAlumnoSeguro();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ElimarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ElimarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ElimarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ElimarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ElimarAlumno().setVisible(true);
        });
    }

    /** Rellena los campos de teléfono y correo con los datos del alumno seleccionado en la tabla. */
    private void cargarDatosAlumnoSeleccionado() {
        int filaVista = jTable1.getSelectedRow();

        if (filaVista == -1) {
            return;
        }

        int filaModelo = jTable1.convertRowIndexToModel(filaVista);

        Object telefono = jTable1.getModel().getValueAt(filaModelo, 4);
        Object correo = jTable1.getModel().getValueAt(filaModelo, 5);

        jTextField1.setText(telefono == null ? "" : telefono.toString());
        jTextField2.setText(correo == null ? "" : correo.toString());
    }

    /** Verifica que los datos introducidos coincidan con el alumno de la tabla y, tras confirmar, lo elimina junto con sus matrículas y líneas de matrícula. */
    private void eliminarAlumnoSeleccionado() {
        int filaVista = jTable1.getSelectedRow();

        if (filaVista == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar el alumno de la tabla.");
            return;
        }

        String telefonoIntroducido = jTextField1.getText().trim();
        String correoIntroducido = jTextField2.getText().trim();

        if (telefonoIntroducido.isEmpty() || correoIntroducido.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes introducir teléfono y correo.");
            return;
        }

        int filaModelo = jTable1.convertRowIndexToModel(filaVista);

        Object codigoObj = jTable1.getModel().getValueAt(filaModelo, 0);
        Object nombreObj = jTable1.getModel().getValueAt(filaModelo, 1);
        Object telefonoObj = jTable1.getModel().getValueAt(filaModelo, 4);
        Object correoObj = jTable1.getModel().getValueAt(filaModelo, 5);

        int codigoAlumno;

        try {
            codigoAlumno = Integer.parseInt(codigoObj.toString());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El código del alumno no es válido.");
            return;
        }

        String telefonoTabla = telefonoObj == null ? "" : telefonoObj.toString().trim();
        String correoTabla = correoObj == null ? "" : correoObj.toString().trim();

        if (!telefonoIntroducido.equals(telefonoTabla) || !correoIntroducido.equals(correoTabla)) {
            JOptionPane.showMessageDialog(this,
                    "Los datos introducidos no coinciden con el alumno seleccionado.\n\n"
                    + "Teléfono introducido: " + telefonoIntroducido + "\n"
                    + "Teléfono tabla: " + telefonoTabla + "\n\n"
                    + "Correo introducido: " + correoIntroducido + "\n"
                    + "Correo tabla: " + correoTabla);
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(
                this,
                "Vas a eliminar al alumno:\n\n"
                + "Código: " + codigoAlumno + "\n"
                + "Nombre: " + nombreObj + "\n"
                + "Teléfono: " + telefonoTabla + "\n"
                + "Correo: " + correoTabla + "\n\n"
                + "También se eliminarán sus matrículas y líneas de matrícula.\n"
                + "¿Seguro que quieres continuar?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        boolean eliminado = GestionBaseDeDatos.eliminarAlumnoCompletoPorCodigoTelefonoCorreo(
                codigoAlumno,
                telefonoIntroducido,
                correoIntroducido
        );

        if (eliminado) {
            JOptionPane.showMessageDialog(this, "Alumno eliminado correctamente.");

            jTextField1.setText("");
            jTextField2.setText("");
            configurarTablaVacia();

        } else {
            JOptionPane.showMessageDialog(this,
                    "No se pudo eliminar el alumno.\n"
                    + "Comprueba que el código, teléfono y correo coinciden.");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEliminar;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
