/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Crear;

import Utils.*;
import javax.swing.JOptionPane;
import servicios.BaseDeDatos.GestionBaseDeDatos;
import java.util.HashMap;
import servicios.BaseDeDatos.ConsultasSQL;

/**
 *
 * @author Rich
 */
public class CrearLineaMatricula extends javax.swing.JFrame {

    private int idMatricula = -1;
    private int idCicloSeleccionado = -1;
    private int idModuloSeleccionado = -1;

    private HashMap<String, Integer> mapaCiclos = new HashMap<>();
    private HashMap<String, Integer> mapaModulos = new HashMap<>();

    /**
     * Creates new form FormularioLineaMatriucla
     *
     * @param idMatricula
     */
    public CrearLineaMatricula(int idMatricula) {
        initComponents();

        this.idMatricula = idMatricula;

        configurarVentana();
        cargarCiclos();
    }

    private void configurarVentana() {
        setLocationRelativeTo(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                cancelar();
            }
        });

        jButtonGuardar.setText("Añadir módulo");

        jLabelInfoCiclo.setText("Ciclo:");

        jComboBoxCiclos.removeAllItems();

        jComboBoxCiclos.addActionListener(e -> cicloSeleccionado());
    }

    private void cargarCiclos() {
        jComboBoxCiclos.removeAllItems();

        mapaCiclos.clear();
        mapaModulos.clear();

        jComboBoxCiclos.addItem("Selecciona un ciclo");

        for (ItemCombo ciclo : GestionBaseDeDatos.obtenerCiclosCombo()) {
            String texto = ciclo.toString();

            jComboBoxCiclos.addItem(texto);
            mapaCiclos.put(texto, ciclo.getId());
        }
    }

    private void cicloSeleccionado() {
        Object seleccionado = jComboBoxCiclos.getSelectedItem();

        if (seleccionado == null) {
            return;
        }

        String textoSeleccionado = seleccionado.toString();

        if (!mapaCiclos.containsKey(textoSeleccionado)) {
            idCicloSeleccionado = -1;
            idModuloSeleccionado = -1;

            return;
        }

        idCicloSeleccionado = mapaCiclos.get(textoSeleccionado);

    }

    private void cancelar() {
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres cancelar? Se perderá todo lo creado en este proceso.",
                "Cancelar creación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            GestionBaseDeDatos.cancelarTransaccion();
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInfoRepeticion = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jLabelInfoPrimeraCalificacion = new javax.swing.JLabel();
        jTextFieldSegundaCalificacion = new javax.swing.JTextField();
        jTextFieldPrimerCalificacion = new javax.swing.JTextField();
        jLabelInfoSegundaCalificacion = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelInfoCiclo = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jComboBoxCiclos = new javax.swing.JComboBox<>();
        jTextFieldRepeticion = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelInfoRepeticion.setText("Repeticion:");

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabelInfoPrimeraCalificacion.setText("1ª Calificacion: ");

        jTextFieldSegundaCalificacion.setPreferredSize(new java.awt.Dimension(64, 128));

        jTextFieldPrimerCalificacion.setPreferredSize(new java.awt.Dimension(64, 128));

        jLabelInfoSegundaCalificacion.setText("2ª Calificacion:");

        jLabelTitulo.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("RELLENAR LINEA-MATRICULA");

        jLabelInfoCiclo.setText("Ciclo:");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jComboBoxCiclos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldRepeticion.setPreferredSize(new java.awt.Dimension(64, 128));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(515, 515, 515)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelInfoCiclo)
                    .addComponent(jLabelInfoRepeticion)
                    .addComponent(jLabelInfoSegundaCalificacion)
                    .addComponent(jLabelInfoPrimeraCalificacion))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxCiclos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldPrimerCalificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldSegundaCalificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldRepeticion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(380, 380, 380))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCancelar)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonGuardar)
                        .addGap(526, 526, 526))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelInfoCiclo)
                            .addComponent(jComboBoxCiclos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelInfoRepeticion)
                            .addComponent(jTextFieldRepeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelInfoPrimeraCalificacion)
                            .addComponent(jTextFieldPrimerCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelInfoSegundaCalificacion)
                            .addComponent(jTextFieldSegundaCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        crearLinea();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres cancelar? Se perderá todo lo creado en este proceso.",
                "Cancelar creación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            GestionBaseDeDatos.cancelarTransaccion();
            this.dispose();
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearLineaMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearLineaMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearLineaMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearLineaMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CrearLineaMatricula(1).setVisible(true);
        });
    }

    private void crearLinea() {

        if (idMatricula == -1) {
            JOptionPane.showMessageDialog(this, "No hay matrícula asociada.");
            return;
        }

        if (idCicloSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un ciclo.");
            return;
        }

        if (idModuloSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un módulo.");
            return;
        }

        String repeticionTexto = jTextFieldRepeticion.getText().trim();
        String primeraCalificacionTexto = jTextFieldPrimerCalificacion.getText().trim().replace(",", ".");
        String segundaCalificacionTexto = jTextFieldSegundaCalificacion.getText().trim().replace(",", ".");

        if (!Validadores.validarTextoNoVacio(repeticionTexto)
                || !Validadores.validarTextoNoVacio(primeraCalificacionTexto)
                || !Validadores.validarTextoNoVacio(segundaCalificacionTexto)) {

            JOptionPane.showMessageDialog(this, "Debes rellenar repetición y calificaciones.");
            return;
        }

        int repeticion;
        double primeraCalificacion;
        double segundaCalificacion;

        try {
            repeticion = Integer.parseInt(repeticionTexto);
            primeraCalificacion = Double.parseDouble(primeraCalificacionTexto);
            segundaCalificacion = Double.parseDouble(segundaCalificacionTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Repetición y calificaciones deben ser numéricas.");
            return;
        }

        if (repeticion < 0) {
            JOptionPane.showMessageDialog(this, "La repetición no puede ser negativa.");
            return;
        }

        if (primeraCalificacion < 0 || primeraCalificacion > 10
                || segundaCalificacion < 0 || segundaCalificacion > 10) {

            JOptionPane.showMessageDialog(this, "Las calificaciones deben estar entre 0 y 10.");
            return;
        }

        String[] datos = {
            String.valueOf(idMatricula),
            String.valueOf(idModuloSeleccionado),
            String.valueOf(repeticion),
            String.valueOf(primeraCalificacion),
            String.valueOf(segundaCalificacion)
        };

        boolean insertado = GestionBaseDeDatos.insertarSinID(ConsultasSQL.INSERT_LINEA_MATRICULA[1],datos);

        if (insertado) {
            JOptionPane.showMessageDialog(this, "Módulo añadido correctamente a la matrícula.");

            int opcion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Quieres añadir otro módulo a esta matrícula?",
                    "Añadir otro módulo",
                    JOptionPane.YES_NO_OPTION
            );

            if (opcion == JOptionPane.YES_OPTION) {
                limpiarCamposParciales();
            } else {
                GestionBaseDeDatos.confirmarTransaccion();
                JOptionPane.showMessageDialog(this, "Matrícula guardada definitivamente.");
                this.dispose();
            }

        } else {
            GestionBaseDeDatos.cancelarTransaccion();
            JOptionPane.showMessageDialog(this, "Error al añadir el módulo. Se ha cancelado todo el proceso.");
        }
    }

    private void limpiarCamposParciales() {
        idCicloSeleccionado = -1;
        idModuloSeleccionado = -1;

        jComboBoxCiclos.setSelectedIndex(0);

        jTextFieldRepeticion.setText("");
        jTextFieldPrimerCalificacion.setText("");
        jTextFieldSegundaCalificacion.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<String> jComboBoxCiclos;
    private javax.swing.JLabel jLabelInfoCiclo;
    private javax.swing.JLabel jLabelInfoPrimeraCalificacion;
    private javax.swing.JLabel jLabelInfoRepeticion;
    private javax.swing.JLabel jLabelInfoSegundaCalificacion;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldPrimerCalificacion;
    private javax.swing.JTextField jTextFieldRepeticion;
    private javax.swing.JTextField jTextFieldSegundaCalificacion;
    // End of variables declaration//GEN-END:variables
}
