/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Crear;

import Utils.*;
import javax.swing.JOptionPane;
import servicios.BaseDeDatos.GestionBaseDeDatos;
import java.util.HashMap;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import servicios.BaseDeDatos.ConsultasSQL;

/**
 * Formulario Swing para añadir líneas de matrícula (módulos) a una matrícula
 * existente. Permite seleccionar un ciclo, introducir repetición y
 * calificaciones, e insertar tantos módulos como se desee antes de confirmar la
 * transacción.
 *
 * @author Rich
 */
public class CrearLineaMatricula extends javax.swing.JFrame {

    private int idMatricula = -1;
    private int idCicloSeleccionado = -1;
    private int idModuloSeleccionado = -1;

    private final HashMap<String, Integer> mapaCiclos = new HashMap<>();
    private final HashMap<String, Integer> mapaModulos = new HashMap<>();

    /**
     * Creates new form FormularioLineaMatriucla
     *
     * @param idMatricula
     */
    public CrearLineaMatricula(int idMatricula) {
        initComponents();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        this.idMatricula = idMatricula;

        configurarVentana();

        configurarTabla(); // AÑADIR ESTO

        cargarCiclos();
    }

    /**
     * Configura el cierre con confirmación, inicializa el combo de ciclos y
     * registra el listener de selección.
     */
    private void configurarVentana() {
        setLocationRelativeTo(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                cancelar();
            }
        });

        jLabelInfoCiclo.setText("Ciclo:");

        jComboBoxCiclos.removeAllItems();

        jComboBoxCiclos.addActionListener(e -> cicloSeleccionado());
    }

    /**
     * Consulta los ciclos disponibles en la BD y los carga en el combo,
     * actualizando el mapa de IDs.
     */
    private void cargarCiclos() {
        jComboBoxCiclos.removeAllItems();

        mapaCiclos.clear();
        mapaModulos.clear();

        jComboBoxCiclos.addItem("Selecciona un ciclo");

        for (ItemCombo ciclo : GestionBaseDeDatos.obtenerCiclosCombo()) {
            String texto = ciclo.toString();

            jComboBoxCiclos.addItem(texto);
            mapaCiclos.put(texto, ciclo.getId());
        }
    }

    /**
     * Actualiza {@code idCicloSeleccionado} cuando el usuario elige un ciclo en
     * el combo.
     */
    private void cicloSeleccionado() {

        Object seleccionado = jComboBoxCiclos.getSelectedItem();

        if (seleccionado == null) {
            return;
        }

        String textoSeleccionado = seleccionado.toString();

        if (!mapaCiclos.containsKey(textoSeleccionado)) {

            idCicloSeleccionado = -1;
            idModuloSeleccionado = -1;

            return;
        }

        idCicloSeleccionado = mapaCiclos.get(textoSeleccionado);

        cargarModulosPorCiclo(idCicloSeleccionado); // AÑADIR
    }

    private void cargarModulosPorCiclo(int idCiclo) {

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        modelo.setRowCount(0);

        mapaModulos.clear();

        /*
        EJEMPLO:
        Debes crear este método en GestionBaseDeDatos
        que devuelva una lista de ItemCombo
         */
        for (ItemCombo modulo : GestionBaseDeDatos.obtenerModulosPorCicloCombo(idCiclo)) {

            modelo.addRow(new Object[]{
                modulo.getId(),
                modulo.toString()
            });

            mapaModulos.put(modulo.toString(), modulo.getId());
        }
    }

    /**
     * Pide confirmación y, si el usuario acepta, cancela la transacción activa
     * y cierra la ventana.
     */
    private void cancelar() {
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres cancelar? Se perderá todo lo creado en este proceso.",
                "Cancelar creación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            GestionBaseDeDatos.cancelarTransaccion();
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInfoRepeticion = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jLabelInfoPrimeraCalificacion = new javax.swing.JLabel();
        jTextFieldSegundaCalificacion = new javax.swing.JTextField();
        jTextFieldPrimeraCalificacion = new javax.swing.JTextField();
        jLabelInfoSegundaCalificacion = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelInfoCiclo = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jComboBoxCiclos = new javax.swing.JComboBox<>();
        jTextFieldRepeticion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelInfoRepeticion.setText("Repeticion:");

        jButtonGuardar.setBackground(new java.awt.Color(75, 75, 75));
        jButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabelInfoPrimeraCalificacion.setText("1ª Calificacion: ");

        jTextFieldSegundaCalificacion.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldSegundaCalificacion.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldSegundaCalificacion.setPreferredSize(new java.awt.Dimension(64, 128));

        jTextFieldPrimeraCalificacion.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldPrimeraCalificacion.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldPrimeraCalificacion.setPreferredSize(new java.awt.Dimension(64, 128));
        jTextFieldPrimeraCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrimeraCalificacionActionPerformed(evt);
            }
        });

        jLabelInfoSegundaCalificacion.setText("2ª Calificacion:");

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("RELLENAR LINEA-MATRICULA");

        jLabelInfoCiclo.setText("Ciclo:");

        jButtonCancelar.setBackground(new java.awt.Color(75, 75, 75));
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jComboBoxCiclos.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxCiclos.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxCiclos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCiclos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCiclosActionPerformed(evt);
            }
        });

        jTextFieldRepeticion.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldRepeticion.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldRepeticion.setPreferredSize(new java.awt.Dimension(64, 128));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelInfoPrimeraCalificacion)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelInfoCiclo)
                                    .addComponent(jLabelInfoRepeticion)
                                    .addComponent(jLabelInfoSegundaCalificacion)
                                    .addComponent(jButtonCancelar))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jButtonGuardar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBoxCiclos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextFieldPrimeraCalificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextFieldSegundaCalificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextFieldRepeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(41, 41, 41)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelInfoCiclo)
                            .addComponent(jComboBoxCiclos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelInfoRepeticion)
                            .addComponent(jTextFieldRepeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelInfoPrimeraCalificacion)
                            .addComponent(jTextFieldPrimeraCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelInfoSegundaCalificacion)
                            .addComponent(jTextFieldSegundaCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonGuardar)
                            .addComponent(jButtonCancelar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        crearLinea();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres cancelar? Se perderá todo lo creado en este proceso.",
                "Cancelar creación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            GestionBaseDeDatos.cancelarTransaccion();
            this.dispose();
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldPrimeraCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrimeraCalificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrimeraCalificacionActionPerformed

    private void jComboBoxCiclosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCiclosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCiclosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearLineaMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearLineaMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearLineaMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearLineaMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CrearLineaMatricula(1).setVisible(true);
        });
    }

    /**
     * Valida los datos introducidos, inserta la línea de matrícula y pregunta
     * si se desea añadir otro módulo o confirmar la transacción.
     */
    private void crearLinea() {

        int repeticion = 0;
        double primeraCalificacion = 0;
        double segundaCalificacion = 0;

        if (idMatricula == -1) {
            JOptionPane.showMessageDialog(this, "No hay matrícula asociada.");
            return;
        }

        if (idCicloSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un ciclo.");
            return;
        }

        if (idModuloSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un módulo de la lista.");
            return;
        }

        String repeticionTexto = jTextFieldRepeticion.getText().trim();
        String temp1 = jTextFieldPrimeraCalificacion.getText().trim().replace(",", ".");
        String temp2 = jTextFieldSegundaCalificacion.getText().trim().replace(",", ".");

        if (!Validadores.validarTextoNoVacio(repeticionTexto)) {

            JOptionPane.showMessageDialog(this, "Debes rellenar repetición.");
            return;
        }

        try {
            primeraCalificacion = Validadores.validarTextoNoVacio(temp1) ? Double.parseDouble(temp1) : 0;
            segundaCalificacion = Validadores.validarTextoNoVacio(temp2) ? Double.parseDouble(temp2) : 0;
            repeticion = Integer.parseInt(repeticionTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Repetición y calificaciones deben ser números.");
            return;
        }
        if (!Validadores.validarRepeticion(repeticion)) {
            JOptionPane.showMessageDialog(this, "La repetición debe ser 1 o mayor.");
            return;
        }
        if (!Validadores.validarCalificacion(primeraCalificacion)) {
            JOptionPane.showMessageDialog(this, "La primera calificación debe estar entre 0 y 10.");
            return;
        }
        if (!Validadores.validarCalificacion(segundaCalificacion)) {
            JOptionPane.showMessageDialog(this, "La segunda calificación debe estar entre 0 y 10.");
            return;
        }
        
        String[] datos = {
            String.valueOf(idMatricula),
            String.valueOf(idModuloSeleccionado),
            String.valueOf(repeticion),
            String.valueOf(primeraCalificacion),
            String.valueOf(segundaCalificacion)
        };

        boolean insertado = GestionBaseDeDatos.insertarSinID(ConsultasSQL.INSERT_LINEA_MATRICULA[1], datos);

        if (insertado) {
            JOptionPane.showMessageDialog(this, "Módulo añadido correctamente a la matrícula.");

            int opcion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Quieres añadir otro módulo a esta matrícula?",
                    "Añadir otro módulo",
                    JOptionPane.YES_NO_OPTION
            );

            if (opcion == JOptionPane.YES_OPTION) {
                limpiarCamposParciales();
            } else {
                GestionBaseDeDatos.confirmarTransaccion();
                JOptionPane.showMessageDialog(this, "Matrícula guardada definitivamente.");
                this.dispose();
            }

        } else {
            GestionBaseDeDatos.cancelarTransaccion();
            JOptionPane.showMessageDialog(this, "Error al añadir el módulo. Se ha cancelado todo el proceso.");
        }
    }

    private void configurarTabla() {

        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{"ID", "Módulo"},
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        jTable1.setModel(modelo);

        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        jTable1.getSelectionModel().addListSelectionListener(e -> {

            if (!e.getValueIsAdjusting()) {

                int fila = jTable1.getSelectedRow();

                if (fila != -1) {

                    idModuloSeleccionado = Integer.parseInt(
                            jTable1.getValueAt(fila, 0).toString()
                    );

                    System.out.println("Modulo seleccionado: " + idModuloSeleccionado);
                }
            }
        });
    }

    /**
     * Restablece el combo y los campos de repetición y calificaciones para
     * introducir otro módulo.
     */
    private void limpiarCamposParciales() {
        idCicloSeleccionado = -1;
        idModuloSeleccionado = -1;

        jComboBoxCiclos.setSelectedIndex(0);

        jTextFieldRepeticion.setText("");
        jTextFieldPrimeraCalificacion.setText("");
        jTextFieldSegundaCalificacion.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<String> jComboBoxCiclos;
    private javax.swing.JLabel jLabelInfoCiclo;
    private javax.swing.JLabel jLabelInfoPrimeraCalificacion;
    private javax.swing.JLabel jLabelInfoRepeticion;
    private javax.swing.JLabel jLabelInfoSegundaCalificacion;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldPrimeraCalificacion;
    private javax.swing.JTextField jTextFieldRepeticion;
    private javax.swing.JTextField jTextFieldSegundaCalificacion;
    // End of variables declaration//GEN-END:variables
}
