/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Crear;

import Utils.Validadores;
import javax.swing.JOptionPane;
import servicios.BaseDeDatos.ConsultasSQL;
import servicios.BaseDeDatos.GestionBaseDeDatos;

/**
 *
 * @author Rich
 */
public class CrearMatricula extends javax.swing.JFrame {

    private int idAlumno = -1;

    /**
     * Creates new form FormularioMatricula
     *
     * @param idAlumno
     */
    public CrearMatricula(int idAlumno) {
        initComponents();

        this.idAlumno = idAlumno;
        configurarVentana();
        jTextFieldCodigoAlumno.setText(String.valueOf(idAlumno));
        jTextFieldCodigoAlumno.setEditable(false);
    }

    private void configurarVentana() {
         setLocationRelativeTo(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                cancelar();
            }
        });

        jButtonGuardar.setText("Crear matrícula");
    }

    private void cancelar() {
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres cancelar? Se perderá todo lo creado en este proceso.",
                "Cancelar creación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            GestionBaseDeDatos.cancelarTransaccion();
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInfoEstado = new javax.swing.JLabel();
        jLabelInfoImporte = new javax.swing.JLabel();
        jLabelInfoAnioAcademico = new javax.swing.JLabel();
        jLabelInfoCodigoAlumno = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jTextFieldEstado = new javax.swing.JTextField();
        jTextFieldImporte = new javax.swing.JTextField();
        jTextFieldCodigoAlumno = new javax.swing.JTextField();
        jTextFieldAnioAcademico = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jLabelInfoActiva = new javax.swing.JLabel();
        jLabelInfoEuros = new javax.swing.JLabel();
        jLabelInfoEuros1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelInfoEstado.setText("Estado:");

        jLabelInfoImporte.setText("Importe:");

        jLabelInfoAnioAcademico.setText("Año Académico:");

        jLabelInfoCodigoAlumno.setText("Codigo del Alumno:");

        jLabelTitulo.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("RELLENAR MATRICULA");

        jButtonGuardar.setText("Siguiente");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jTextFieldEstado.setMinimumSize(new java.awt.Dimension(64, 128));
        jTextFieldEstado.setPreferredSize(new java.awt.Dimension(64, 128));

        jTextFieldImporte.setMinimumSize(new java.awt.Dimension(64, 128));
        jTextFieldImporte.setPreferredSize(new java.awt.Dimension(64, 128));
        jTextFieldImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldImporteActionPerformed(evt);
            }
        });

        jTextFieldCodigoAlumno.setPreferredSize(new java.awt.Dimension(64, 128));

        jTextFieldAnioAcademico.setPreferredSize(new java.awt.Dimension(64, 128));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelInfoActiva.setText("Activa/No Activa");

        jLabelInfoEuros.setText("Euros");

        jLabelInfoEuros1.setText("Formato 20XX/20XX +1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(471, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(397, 397, 397))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelInfoAnioAcademico)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelInfoCodigoAlumno)
                                        .addGap(86, 86, 86))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelInfoImporte, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelInfoEstado, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(59, 59, 59)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldAnioAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelInfoEuros1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelInfoEuros))
                                    .addComponent(jTextFieldCodigoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelInfoActiva)))))
                        .addGap(353, 353, 353))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGuardar)
                        .addGap(495, 495, 495))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInfoEstado)
                    .addComponent(jLabelInfoActiva))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInfoImporte)
                    .addComponent(jLabelInfoEuros))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInfoAnioAcademico)
                    .addComponent(jTextFieldAnioAcademico, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInfoEuros1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInfoCodigoAlumno)
                    .addComponent(jTextFieldCodigoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(238, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldImporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldImporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldImporteActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres cancelar? Se perderá todo lo creado en este proceso.",
                "Cancelar creación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            GestionBaseDeDatos.cancelarTransaccion();
            this.dispose();
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        crearMatricula();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CrearMatricula(1).setVisible(true);
        });
    }

    private void crearMatricula() {

        String estado = jTextFieldEstado.getText().trim();
        String importeTexto = jTextFieldImporte.getText().trim().replace(",", ".");
        String anioAcademico = jTextFieldAnioAcademico.getText().trim();
        String codigoAlumnoTexto = jTextFieldCodigoAlumno.getText().trim();

        if (!Validadores.validarTextoNoVacio(estado)
                || !Validadores.validarTextoNoVacio(importeTexto)
                || !Validadores.validarTextoNoVacio(anioAcademico)
                || !Validadores.validarTextoNoVacio(codigoAlumnoTexto)) {

            JOptionPane.showMessageDialog(this, "Debes rellenar todos los campos.");
            return;
        }

        double importe;

        try {
            importe = Double.parseDouble(importeTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El importe debe ser un número válido.");
            return;
        }

        int codigoAlumno;

        try {
            codigoAlumno = Integer.parseInt(codigoAlumnoTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El código del alumno debe ser un número entero.");
            return;
        }

        String[] datos = {
            estado,
            String.valueOf(importe),
            anioAcademico,
            String.valueOf(codigoAlumno)
        };

        int idMatricula = GestionBaseDeDatos.insertarYDevolverID(ConsultasSQL.INSERT_MATRICULA[0],datos);

        if (idMatricula != -1) {
            JOptionPane.showMessageDialog(this, "Matrícula creada correctamente con ID: " + idMatricula);

            new CrearLineaMatricula(idMatricula).setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Error al crear la matrícula.");
        }
    }

    private void limpiarCampos() {
        jTextFieldEstado.setText("");
        jTextFieldImporte.setText("");
        jTextFieldAnioAcademico.setText("");

        if (idAlumno == -1) {
            jTextFieldCodigoAlumno.setText("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabelInfoActiva;
    private javax.swing.JLabel jLabelInfoAnioAcademico;
    private javax.swing.JLabel jLabelInfoCodigoAlumno;
    private javax.swing.JLabel jLabelInfoEstado;
    private javax.swing.JLabel jLabelInfoEuros;
    private javax.swing.JLabel jLabelInfoEuros1;
    private javax.swing.JLabel jLabelInfoImporte;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldAnioAcademico;
    private javax.swing.JTextField jTextFieldCodigoAlumno;
    private javax.swing.JTextField jTextFieldEstado;
    private javax.swing.JTextField jTextFieldImporte;
    // End of variables declaration//GEN-END:variables
}
