package pantallas.Crear;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import Control.SesionDatos;
import Utils.Validadores;
import javax.swing.JOptionPane;
import modelos.Ciclo;
import servicios.BaseDeDatos.GestionBaseDeDatos;
import servicios.BaseDeDatos.ConsultasSQL;

/**
 * Formulario Swing para registrar un nuevo ciclo formativo en la base de datos.
 * Recoge denominación, familia profesional, nivel, horas y año curricular;
 * tras insertar el ciclo, abre el formulario de gestión de módulos del ciclo creado.
 *
 * @author Rich
 */
public class CrearCiclo extends javax.swing.JFrame {

    /**
     * Creates new form FormularioCiclo
     */
    public CrearCiclo() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        configurarVentana();
    }

    /** Configura el título, el cierre con confirmación y los campos de solo lectura (familia, nivel, horas). */
    private void configurarVentana() {
        setLocationRelativeTo(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                cancelar();
            }
        });

        setTitle("Crear ciclo");
        jComboBoxNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"basico", "medio", "superior"}));
    }

    /** Pide confirmación y, si el usuario acepta, cancela la transacción activa y cierra la ventana. */
    private void cancelar() {
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres cancelar? Se perderá todo lo creado en este proceso.",
                "Cancelar creación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            GestionBaseDeDatos.cancelarTransaccion();
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldFamiliaProfresional = new javax.swing.JTextField();
        jTextFieldAñoCurricular = new javax.swing.JTextField();
        jTextFieldHoras = new javax.swing.JTextField();
        jLabelInfoDenominacion = new javax.swing.JLabel();
        jLabelInfoFamiliaProfesional = new javax.swing.JLabel();
        jLabelInfoNombre3 = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jLabelInfoNombre4 = new javax.swing.JLabel();
        jLabelInfoAñoCurricular = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldDenominacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxNivel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldFamiliaProfresional.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFamiliaProfresional.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldFamiliaProfresional.setMinimumSize(new java.awt.Dimension(64, 128));
        jTextFieldFamiliaProfresional.setPreferredSize(new java.awt.Dimension(64, 128));
        jTextFieldFamiliaProfresional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFamiliaProfresionalActionPerformed(evt);
            }
        });

        jTextFieldAñoCurricular.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldAñoCurricular.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldAñoCurricular.setPreferredSize(new java.awt.Dimension(64, 128));

        jTextFieldHoras.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldHoras.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldHoras.setPreferredSize(new java.awt.Dimension(64, 128));

        jLabelInfoDenominacion.setText("Denominación:");

        jLabelInfoFamiliaProfesional.setText("Familia profesional:");

        jLabelInfoNombre3.setText("Nivel:");

        jButtonGuardar.setBackground(new java.awt.Color(75, 75, 75));
        jButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setText("Siguiente");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabelInfoNombre4.setText("Horas:");

        jLabelInfoAñoCurricular.setText("AñoCurricular");

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("CREAR CICLO");

        jButtonCancelar.setBackground(new java.awt.Color(75, 75, 75));
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTextFieldDenominacion.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDenominacion.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setText("Ej: 2024");

        jComboBoxNivel.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxNivel.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonGuardar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelInfoAñoCurricular)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelInfoFamiliaProfesional)
                                            .addComponent(jLabelInfoDenominacion))
                                        .addGap(4, 4, 4))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelInfoNombre3)
                                        .addComponent(jLabelInfoNombre4)))
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldHoras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldFamiliaProfresional, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldDenominacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                                    .addComponent(jTextFieldAñoCurricular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxNivel, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelInfoDenominacion)
                    .addComponent(jTextFieldDenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFamiliaProfresional, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInfoFamiliaProfesional))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInfoNombre3)
                    .addComponent(jComboBoxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInfoNombre4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAñoCurricular, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInfoAñoCurricular)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFamiliaProfresionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFamiliaProfresionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFamiliaProfresionalActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres cancelar? Se perderá todo lo creado en este proceso.",
                "Cancelar creación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            GestionBaseDeDatos.cancelarTransaccion();
            this.dispose();
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        crearCiclo();
    }//GEN-LAST:event_jButtonGuardarActionPerformed
    // TODO add your handling code here:


    private void jComboBoxCiclosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCiclosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCiclosActionPerformed

    /**
     * Punto de entrada para pruebas aisladas del formulario.
     *
     * @param args Argumentos de línea de comandos (no utilizados).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCiclo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CrearCiclo().setVisible(true);
        });
    }

    /** Valida los campos, inicia una transacción, inserta el ciclo en la BD y abre el formulario de módulos si el insert es correcto. */
    private void crearCiclo() {

        String familia = jTextFieldFamiliaProfresional.getText().trim();
        String nivel = jComboBoxNivel.getSelectedItem().toString();
        String horasTexto = jTextFieldHoras.getText().trim();
        String anioTexto = jTextFieldAñoCurricular.getText().trim();
        String denominacion = jTextFieldDenominacion.getText().trim();

        if (!Validadores.validarTextoNoVacio(denominacion)) {
            JOptionPane.showMessageDialog(this, "La denominación no puede estar vacía.");
            return;
        }
        if (!Validadores.validarTextoNoVacio(familia)) {
            JOptionPane.showMessageDialog(this, "La familia profesional no puede estar vacía.");
            return;
        }
        if (!Validadores.validarNivel(nivel)) {
            JOptionPane.showMessageDialog(this, "Nivel inválido. Debe ser Basico, Medio o Superior.");
            return;
        }
        if (!Validadores.validarTextoNoVacio(horasTexto)) {
            JOptionPane.showMessageDialog(this, "Las horas no pueden estar vacías.");
            return;
        }
        if (!Validadores.validarTextoNoVacio(anioTexto)) {
            JOptionPane.showMessageDialog(this, "El año curricular no puede estar vacío.");
            return;
        }

        int horas;
        int anioCurricular;

        try {
            horas = Integer.parseInt(horasTexto);
            anioCurricular = Integer.parseInt(anioTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Las horas y el año curricular deben ser números enteros.");
            return;
        }
        
        if (!Validadores.validarHorasCiclo(horas)) {
            JOptionPane.showMessageDialog(this, "Las horas deben ser mayores que 0.");
            return;
        }
        if (!Validadores.validarAñoCurriculum(anioCurricular)) {
            JOptionPane.showMessageDialog(this, "El año curricular debe estar entre 1900 y 3000.");
            return;
        }

        String[] datos = {
            denominacion,
            familia,
            nivel,
            String.valueOf(horas),
            String.valueOf(anioCurricular)
        };

        GestionBaseDeDatos.iniciarTransaccion();

        int idCiclo = GestionBaseDeDatos.insertarYDevolverID(ConsultasSQL.INSERT_CICLO[1],datos);

        if (idCiclo != -1) {
            JOptionPane.showMessageDialog(this, "Ciclo creado correctamente con ID: " + idCiclo);

            Ciclo ciclo = new Ciclo(new String[]{
                String.valueOf(idCiclo), denominacion, familia, nivel,
                String.valueOf(horas), String.valueOf(anioCurricular)
            });
            SesionDatos.registrarCiclo(ciclo, false);

            new GestionarModulosCiclo(idCiclo).setVisible(true);
            this.dispose();

        } else {
            GestionBaseDeDatos.cancelarTransaccion();
            JOptionPane.showMessageDialog(this, "Error al crear el ciclo. Se ha cancelado todo el proceso.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<String> jComboBoxNivel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelInfoAñoCurricular;
    private javax.swing.JLabel jLabelInfoDenominacion;
    private javax.swing.JLabel jLabelInfoFamiliaProfesional;
    private javax.swing.JLabel jLabelInfoNombre3;
    private javax.swing.JLabel jLabelInfoNombre4;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldAñoCurricular;
    private javax.swing.JTextField jTextFieldDenominacion;
    private javax.swing.JTextField jTextFieldFamiliaProfresional;
    private javax.swing.JTextField jTextFieldHoras;
    // End of variables declaration//GEN-END:variables
}
