package pantallas.Crear;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import Utils.Validadores;
import javax.swing.JOptionPane;
import servicios.BaseDeDatos.GestionBaseDeDatos;
import java.awt.Dimension;
import java.awt.FontMetrics;
import javax.swing.JTextField;

/**
 *
 * @author Rich
 */
public class CrearCiclo extends javax.swing.JFrame {

    /**
     * Creates new form FormularioCiclo
     */
    public CrearCiclo() {
        initComponents();
        configurarVentana();
        cargarComboCiclos();
        configurarEventosCombo();

    }

    private void configurarVentana() {
        setLocationRelativeTo(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                cancelar();
            }
        });

        setTitle("Crear ciclo");
        jButtonGuardar.setText("Crear ciclo");

        jTextFieldFamiliaProfresional.setEditable(false);
        jTextFieldNivel.setEditable(false);
        jTextFieldHoras.setEditable(false);

        jTextFieldFamiliaProfresional.setPreferredSize(new Dimension(220, 25));
        jTextFieldNivel.setPreferredSize(new Dimension(160, 25));
        jTextFieldHoras.setPreferredSize(new Dimension(100, 25));
    }

    private void cancelar() {
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres cancelar? Se perderá todo lo creado en este proceso.",
                "Cancelar creación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            GestionBaseDeDatos.cancelarTransaccion();
            this.dispose();
        }
    }

    private void cargarComboCiclos() {
        jComboBoxCiclos.removeAllItems();

        jComboBoxCiclos.addItem("Selecciona un ciclo");
        jComboBoxCiclos.addItem("DAM");
        jComboBoxCiclos.addItem("DAW");
        jComboBoxCiclos.addItem("ASIR");
        jComboBoxCiclos.addItem("SMR");

        jTextFieldHoras.setEditable(false);
    }

    private void configurarEventosCombo() {
        jComboBoxCiclos.addActionListener(e -> actualizarDatosSegunCiclo());
    }

    private void actualizarDatosSegunCiclo() {
        Object seleccionado = jComboBoxCiclos.getSelectedItem();

        if (seleccionado == null) {
            limpiarDatosAutomaticos();
            ajustarTamanioCamposAutomaticos();
            return;
        }

        String ciclo = seleccionado.toString();

        switch (ciclo) {
            case "DAM":
                jTextFieldFamiliaProfresional.setText("Informática y Comunicaciones");
                jTextFieldNivel.setText("Grado Superior");
                jTextFieldHoras.setText("2000");
                break;

            case "DAW":
                jTextFieldFamiliaProfresional.setText("Informática y Comunicaciones");
                jTextFieldNivel.setText("Grado Superior");
                jTextFieldHoras.setText("2000");
                break;

            case "ASIR":
                jTextFieldFamiliaProfresional.setText("Informática y Comunicaciones");
                jTextFieldNivel.setText("Grado Superior");
                jTextFieldHoras.setText("2000");
                break;

            case "SMR":
                jTextFieldFamiliaProfresional.setText("Informática y Comunicaciones");
                jTextFieldNivel.setText("Grado Medio");
                jTextFieldHoras.setText("2000");
                break;

            default:
                limpiarDatosAutomaticos();
                break;
        }

        ajustarTamanioCamposAutomaticos();
    }

    private void limpiarDatosAutomaticos() {
        jTextFieldFamiliaProfresional.setText("");
        jTextFieldNivel.setText("");
        jTextFieldHoras.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldFamiliaProfresional = new javax.swing.JTextField();
        jTextFieldAñoCurricular = new javax.swing.JTextField();
        jTextFieldHoras = new javax.swing.JTextField();
        jTextFieldNivel = new javax.swing.JTextField();
        jLabelInfoDenominacion = new javax.swing.JLabel();
        jLabelInfoFamiliaProfesional = new javax.swing.JLabel();
        jLabelInfoNombre3 = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jLabelInfoNombre4 = new javax.swing.JLabel();
        jLabelInfoAñoCurricular = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jComboBoxCiclos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldFamiliaProfresional.setMinimumSize(new java.awt.Dimension(64, 128));
        jTextFieldFamiliaProfresional.setPreferredSize(new java.awt.Dimension(64, 128));
        jTextFieldFamiliaProfresional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFamiliaProfresionalActionPerformed(evt);
            }
        });

        jTextFieldAñoCurricular.setPreferredSize(new java.awt.Dimension(64, 128));

        jTextFieldHoras.setPreferredSize(new java.awt.Dimension(64, 128));

        jTextFieldNivel.setPreferredSize(new java.awt.Dimension(64, 128));
        jTextFieldNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNivelActionPerformed(evt);
            }
        });

        jLabelInfoDenominacion.setText("Denominación:");

        jLabelInfoFamiliaProfesional.setText("Familia profesional:");

        jLabelInfoNombre3.setText("Nivel:");

        jButtonGuardar.setText("Siguiente");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabelInfoNombre4.setText("Horas:");

        jLabelInfoAñoCurricular.setText("AñoCurricular");

        jLabelTitulo.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("RELLENAR CICLO");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jComboBoxCiclos.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxCiclos.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxCiclos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxCiclos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCiclosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(454, 454, 454)
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(510, 510, 510)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelInfoAñoCurricular)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelInfoFamiliaProfesional)
                                    .addComponent(jLabelInfoDenominacion))
                                .addGap(4, 4, 4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelInfoNombre3)
                                .addComponent(jLabelInfoNombre4)))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNivel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldHoras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldAñoCurricular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldFamiliaProfresional, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxCiclos, 0, 79, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(571, 571, 571)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonGuardar)))
                .addContainerGap(594, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInfoDenominacion)
                    .addComponent(jComboBoxCiclos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFamiliaProfresional, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInfoFamiliaProfesional))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInfoNombre3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInfoNombre4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAñoCurricular, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInfoAñoCurricular))
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(231, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldFamiliaProfresionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFamiliaProfresionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFamiliaProfresionalActionPerformed

    private void jTextFieldNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNivelActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres cancelar? Se perderá todo lo creado en este proceso.",
                "Cancelar creación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            GestionBaseDeDatos.cancelarTransaccion();
            this.dispose();
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        crearCiclo();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jComboBoxCiclosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCiclosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCiclosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCiclo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CrearCiclo().setVisible(true);
        });
    }

    private void crearCiclo() {

        Object itemSeleccionado = jComboBoxCiclos.getSelectedItem();

        if (itemSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un ciclo.");
            return;
        }

        String denominacion = itemSeleccionado.toString().trim();

        if (denominacion.equals("Selecciona un ciclo")) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un ciclo válido.");
            return;
        }

        String familia = jTextFieldFamiliaProfresional.getText().trim();
        String nivel = jTextFieldNivel.getText().trim();
        String horasTexto = jTextFieldHoras.getText().trim();
        String anioTexto = jTextFieldAñoCurricular.getText().trim();

        if (!Validadores.validarTextoNoVacio(denominacion)
                || !Validadores.validarTextoNoVacio(familia)
                || !Validadores.validarTextoNoVacio(nivel)
                || !Validadores.validarTextoNoVacio(horasTexto)
                || !Validadores.validarTextoNoVacio(anioTexto)) {

            JOptionPane.showMessageDialog(this, "Debes rellenar todos los campos.");
            return;
        }

        int horas;
        int anioCurricular;

        try {
            horas = Integer.parseInt(horasTexto);
            anioCurricular = Integer.parseInt(anioTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Las horas y el año curricular deben ser números enteros.");
            return;
        }

        String[] datos = {
            denominacion,
            familia,
            nivel,
            String.valueOf(horas),
            String.valueOf(anioCurricular)
        };

        GestionBaseDeDatos.iniciarTransaccion();

        int idCiclo = GestionBaseDeDatos.insertarCicloYDevolverID(datos);

        if (idCiclo != -1) {
            JOptionPane.showMessageDialog(this, "Ciclo creado correctamente con ID: " + idCiclo);

            new GestionarModulosCiclo(idCiclo).setVisible(true);
            this.dispose();

        } else {
            GestionBaseDeDatos.cancelarTransaccion();
            JOptionPane.showMessageDialog(this, "Error al crear el ciclo. Se ha cancelado todo el proceso.");
        }
    }

    private void ajustarTamanioTextField(JTextField campo) {
        String texto = campo.getText();

        if (texto == null) {
            texto = "";
        }

        FontMetrics metrics = campo.getFontMetrics(campo.getFont());

        int anchoTexto = metrics.stringWidth(texto);
        int anchoMinimo = 120;
        int margen = 35;

        int anchoFinal = Math.max(anchoMinimo, anchoTexto + margen);
        int altoActual = campo.getPreferredSize().height;

        campo.setPreferredSize(new Dimension(anchoFinal, altoActual));
        campo.setMinimumSize(new Dimension(anchoFinal, altoActual));

        campo.revalidate();
        campo.repaint();
    }

    private void ajustarTamanioCamposAutomaticos() {
        ajustarTamanioTextField(jTextFieldFamiliaProfresional);
        ajustarTamanioTextField(jTextFieldNivel);
        ajustarTamanioTextField(jTextFieldHoras);

        pack();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<String> jComboBoxCiclos;
    private javax.swing.JLabel jLabelInfoAñoCurricular;
    private javax.swing.JLabel jLabelInfoDenominacion;
    private javax.swing.JLabel jLabelInfoFamiliaProfesional;
    private javax.swing.JLabel jLabelInfoNombre3;
    private javax.swing.JLabel jLabelInfoNombre4;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldAñoCurricular;
    private javax.swing.JTextField jTextFieldFamiliaProfresional;
    private javax.swing.JTextField jTextFieldHoras;
    private javax.swing.JTextField jTextFieldNivel;
    // End of variables declaration//GEN-END:variables
}
