/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Crear;

import Utils.*;
import javax.swing.JOptionPane;
import servicios.BaseDeDatos.GestionBaseDeDatos;
import java.util.HashMap;

/**
 *
 * @author Rich
 */
public class CrearLineaMatricula extends javax.swing.JFrame {

    private int idMatricula = -1;
    private int idCicloSeleccionado = -1;
    private int idModuloSeleccionado = -1;

    private HashMap<String, Integer> mapaCiclos = new HashMap<>();
    private HashMap<String, Integer> mapaModulos = new HashMap<>();

    /**
     * Creates new form FormularioLineaMatriucla
     *
     * @param idMatricula
     */
    public CrearLineaMatricula(int idMatricula) {
        initComponents();

        this.idMatricula = idMatricula;

        configurarVentana();
        cargarCiclos();
    }

    private void configurarVentana() {
        setLocationRelativeTo(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                cancelar();
            }
        });

        jButtonGuardar.setText("Añadir módulo");

        jLabelInfoCodigoMatricula.setText("Ciclo:");
        jLabelInfoCodigoModulo.setText("Módulo:");

        jComboBoxCiclos.removeAllItems();
        jComboBoxModulos.removeAllItems();

        jComboBoxCiclos.addActionListener(e -> cicloSeleccionado());
        jComboBoxModulos.addActionListener(e -> moduloSeleccionado());
    }

    private void cargarCiclos() {
        jComboBoxCiclos.removeAllItems();
        jComboBoxModulos.removeAllItems();

        mapaCiclos.clear();
        mapaModulos.clear();

        jComboBoxCiclos.addItem("Selecciona un ciclo");

        for (ItemCombo ciclo : GestionBaseDeDatos.obtenerCiclosCombo()) {
            String texto = ciclo.toString();

            jComboBoxCiclos.addItem(texto);
            mapaCiclos.put(texto, ciclo.getId());
        }
    }

    private void cicloSeleccionado() {
        Object seleccionado = jComboBoxCiclos.getSelectedItem();

        if (seleccionado == null) {
            return;
        }

        String textoSeleccionado = seleccionado.toString();

        if (!mapaCiclos.containsKey(textoSeleccionado)) {
            idCicloSeleccionado = -1;
            idModuloSeleccionado = -1;

            jComboBoxModulos.removeAllItems();
            return;
        }

        idCicloSeleccionado = mapaCiclos.get(textoSeleccionado);

        cargarModulosPorCiclo(idCicloSeleccionado);
    }

    private void cancelar() {
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres cancelar? Se perderá todo lo creado en este proceso.",
                "Cancelar creación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            GestionBaseDeDatos.cancelarTransaccion();
            this.dispose();
        }
    }

    private void cargarModulosPorCiclo(int idCiclo) {
        jComboBoxModulos.removeAllItems();
        mapaModulos.clear();

        jComboBoxModulos.addItem("Selecciona un módulo");

        for (ItemCombo modulo : GestionBaseDeDatos.obtenerModulosPorCicloCombo(idCiclo)) {
            String texto = modulo.toString();

            jComboBoxModulos.addItem(texto);
            mapaModulos.put(texto, modulo.getId());
        }
    }

    private void moduloSeleccionado() {
        Object seleccionado = jComboBoxModulos.getSelectedItem();

        if (seleccionado == null) {
            return;
        }

        String textoSeleccionado = seleccionado.toString();

        if (!mapaModulos.containsKey(textoSeleccionado)) {
            idModuloSeleccionado = -1;
            return;
        }

        idModuloSeleccionado = mapaModulos.get(textoSeleccionado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInfoCodigoModulo = new javax.swing.JLabel();
        jLabelInfoRepeticion = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jLabelInfoPrimeraCalificacion = new javax.swing.JLabel();
        jTextFieldSegundaCalificacion = new javax.swing.JTextField();
        jTextFieldPrimerCalificacion = new javax.swing.JTextField();
        jLabelInfoSegundaCalificacion = new javax.swing.JLabel();
        jTextFieldRepeticion = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelInfoCodigoMatricula = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jComboBoxCiclos = new javax.swing.JComboBox<>();
        jComboBoxModulos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelInfoCodigoModulo.setText("Codigo-Modulo");

        jLabelInfoRepeticion.setText("Repeticion:");

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabelInfoPrimeraCalificacion.setText("1ª Calificacion: ");

        jTextFieldSegundaCalificacion.setPreferredSize(new java.awt.Dimension(64, 128));

        jTextFieldPrimerCalificacion.setPreferredSize(new java.awt.Dimension(64, 128));

        jLabelInfoSegundaCalificacion.setText("2ª Calificacion:");

        jTextFieldRepeticion.setPreferredSize(new java.awt.Dimension(64, 128));
        jTextFieldRepeticion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRepeticionActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("RELLENAR LINEA-MATRICULA");

        jLabelInfoCodigoMatricula.setText("Codigo-Matricula:");

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jComboBoxCiclos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxModulos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(518, 518, 518)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelInfoPrimeraCalificacion)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelInfoCodigoMatricula)
                                .addComponent(jLabelInfoCodigoModulo, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabelInfoRepeticion)
                            .addComponent(jLabelInfoSegundaCalificacion))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonCancelar)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldRepeticion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrimerCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSegundaCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jComboBoxCiclos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(498, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(394, Short.MAX_VALUE)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(380, 380, 380))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInfoCodigoMatricula)
                    .addComponent(jComboBoxCiclos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInfoCodigoModulo)
                    .addComponent(jComboBoxModulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInfoRepeticion)
                    .addComponent(jTextFieldRepeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInfoPrimeraCalificacion)
                    .addComponent(jTextFieldPrimerCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSegundaCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInfoSegundaCalificacion))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(305, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        crearLinea();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTextFieldRepeticionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRepeticionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRepeticionActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres cancelar? Se perderá todo lo creado en este proceso.",
                "Cancelar creación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            GestionBaseDeDatos.cancelarTransaccion();
            this.dispose();
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearLineaMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearLineaMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearLineaMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearLineaMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CrearLineaMatricula(1).setVisible(true);
        });
    }

    private void crearLinea() {

        if (idMatricula == -1) {
            JOptionPane.showMessageDialog(this, "No hay matrícula asociada.");
            return;
        }

        if (idCicloSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un ciclo.");
            return;
        }

        if (idModuloSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un módulo.");
            return;
        }

        String repeticionTexto = jTextFieldRepeticion.getText().trim();
        String primeraCalificacionTexto = jTextFieldPrimerCalificacion.getText().trim().replace(",", ".");
        String segundaCalificacionTexto = jTextFieldSegundaCalificacion.getText().trim().replace(",", ".");

        if (!Validadores.validarTextoNoVacio(repeticionTexto)
                || !Validadores.validarTextoNoVacio(primeraCalificacionTexto)
                || !Validadores.validarTextoNoVacio(segundaCalificacionTexto)) {

            JOptionPane.showMessageDialog(this, "Debes rellenar repetición y calificaciones.");
            return;
        }

        int repeticion;
        double primeraCalificacion;
        double segundaCalificacion;

        try {
            repeticion = Integer.parseInt(repeticionTexto);
            primeraCalificacion = Double.parseDouble(primeraCalificacionTexto);
            segundaCalificacion = Double.parseDouble(segundaCalificacionTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Repetición y calificaciones deben ser numéricas.");
            return;
        }

        if (repeticion < 0) {
            JOptionPane.showMessageDialog(this, "La repetición no puede ser negativa.");
            return;
        }

        if (primeraCalificacion < 0 || primeraCalificacion > 10
                || segundaCalificacion < 0 || segundaCalificacion > 10) {

            JOptionPane.showMessageDialog(this, "Las calificaciones deben estar entre 0 y 10.");
            return;
        }

        String[] datos = {
            String.valueOf(idMatricula),
            String.valueOf(idModuloSeleccionado),
            String.valueOf(repeticion),
            String.valueOf(primeraCalificacion),
            String.valueOf(segundaCalificacion)
        };

        boolean insertado = GestionBaseDeDatos.insertarLineaMatricula(datos);

        if (insertado) {
            JOptionPane.showMessageDialog(this, "Módulo añadido correctamente a la matrícula.");

            int opcion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Quieres añadir otro módulo a esta matrícula?",
                    "Añadir otro módulo",
                    JOptionPane.YES_NO_OPTION
            );

            if (opcion == JOptionPane.YES_OPTION) {
                limpiarCamposParciales();
            } else {
                GestionBaseDeDatos.confirmarTransaccion();
                JOptionPane.showMessageDialog(this, "Matrícula guardada definitivamente.");
                this.dispose();
            }

        } else {
            GestionBaseDeDatos.cancelarTransaccion();
            JOptionPane.showMessageDialog(this, "Error al añadir el módulo. Se ha cancelado todo el proceso.");
        }
    }

    private void limpiarCamposParciales() {
        idCicloSeleccionado = -1;
        idModuloSeleccionado = -1;

        jComboBoxCiclos.setSelectedIndex(0);
        jComboBoxModulos.removeAllItems();

        jTextFieldRepeticion.setText("");
        jTextFieldPrimerCalificacion.setText("");
        jTextFieldSegundaCalificacion.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<String> jComboBoxCiclos;
    private javax.swing.JComboBox<String> jComboBoxModulos;
    private javax.swing.JLabel jLabelInfoCodigoMatricula;
    private javax.swing.JLabel jLabelInfoCodigoModulo;
    private javax.swing.JLabel jLabelInfoPrimeraCalificacion;
    private javax.swing.JLabel jLabelInfoRepeticion;
    private javax.swing.JLabel jLabelInfoSegundaCalificacion;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldPrimerCalificacion;
    private javax.swing.JTextField jTextFieldRepeticion;
    private javax.swing.JTextField jTextFieldSegundaCalificacion;
    // End of variables declaration//GEN-END:variables
}
