/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Crear;

import Control.SesionDatos;
import Utils.ItemCombo;
import Utils.Validadores;
import java.util.HashMap;
import javax.swing.JOptionPane;
import modelos.Modulo;
import servicios.BaseDeDatos.ConsultasSQL;
import servicios.BaseDeDatos.GestionBaseDeDatos;

/**
 * Formulario Swing para registrar un nuevo módulo formativo en la base de datos.
 *
 * <p>Dispone de dos constructores: uno sin argumentos (permite seleccionar el ciclo
 * libremente mediante JComboBox) y otro que recibe el {@code idCiclo} del ciclo padre,
 * preseleccionándolo y bloqueando el combo. También recoge nombre, curso (JComboBox
 * "1" o "2"), créditos ECTS y horas. Los campos se validan con {@link Utils.Validadores}
 * antes del {@code INSERT}. Al guardar se actualiza la lista de módulos en sesión y
 * se regresa a {@link GestionarModulosCiclo}. El cierre solicita confirmación y cancela
 * la transacción activa si el usuario acepta. Se abre desde
 * {@link pantallas.PantallaPrincipal} o desde {@link GestionarModulosCiclo}.</p>
 *
 * @author isard
 * @version 1.0
 */
public class CrearModulo extends javax.swing.JFrame {

    /** Identificador del ciclo seleccionado en el combo; -1 si no hay selección válida. */
    private int idCicloSeleccionado = -1;
    /** Mapa de etiqueta de ciclo a su código entero, para resolver la selección del combo. */
    private final HashMap<String, Integer> mapaCiclos = new HashMap<>();

    /**
     * Construye el formulario sin ciclo asociado (el usuario introduce el
     * código manualmente).
     */
    public CrearModulo() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        configurarVentana();
        cargarCiclos();
    }

    /**
     * Construye el formulario con el ciclo preseleccionado; el campo de código
     * de ciclo se muestra como no editable.
     *
     * @param idCiclo Identificador del ciclo al que pertenecerá el módulo.
     */
    public CrearModulo(int idCiclo) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        configurarVentana();
        cargarCiclos();
        preseleccionarCiclo(idCiclo);
    }

    /**
     * Configura el título, el cierre con confirmación y el texto del botón de
     * guardar.
     */
    private void configurarVentana() {
        setLocationRelativeTo(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                cancelar();
            }
        });

        setTitle("Crear módulo");
        jButtonGuardar.setText("Crear módulo");

        jComboBoxCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1", "2"}));

        jComboBoxCiclos.removeAllItems();
        jComboBoxCiclos.addActionListener(e -> cicloSeleccionado());
    }

    private void cargarCiclos() {
        jComboBoxCiclos.removeAllItems();
        mapaCiclos.clear();
        jComboBoxCiclos.addItem("Selecciona un ciclo");
        for (ItemCombo ciclo : GestionBaseDeDatos.obtenerCiclosCombo()) {
            String texto = ciclo.toString();
            jComboBoxCiclos.addItem(texto);
            mapaCiclos.put(texto, ciclo.getId());
        }
    }

    private void cicloSeleccionado() {
        Object seleccionado = jComboBoxCiclos.getSelectedItem();
        if (seleccionado == null) return;
        String textoSeleccionado = seleccionado.toString();
        if (!mapaCiclos.containsKey(textoSeleccionado)) {
            idCicloSeleccionado = -1;
            return;
        }
        idCicloSeleccionado = mapaCiclos.get(textoSeleccionado);
    }

    private void preseleccionarCiclo(int idCiclo) {
        for (int i = 0; i < jComboBoxCiclos.getItemCount(); i++) {
            String item = jComboBoxCiclos.getItemAt(i);
            if (mapaCiclos.containsKey(item) && mapaCiclos.get(item).equals(idCiclo)) {
                jComboBoxCiclos.setSelectedIndex(i);
                break;
            }
        }
        jComboBoxCiclos.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInfoNombre = new javax.swing.JLabel();
        jLabelInfoCurso = new javax.swing.JLabel();
        jLabelInfoCreditos = new javax.swing.JLabel();
        jLabelInfoNombre3 = new javax.swing.JLabel();
        jLabelInfoNombre4 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCreditos = new javax.swing.JTextField();
        jTextFieldHoras = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jLabelCurso1 = new javax.swing.JLabel();
        jComboBoxCiclos = new javax.swing.JComboBox<>();
        jComboBoxCurso = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelInfoNombre.setText("Nombre:");

        jLabelInfoCurso.setText("Curso:");

        jLabelInfoCreditos.setText("Creditos");

        jLabelInfoNombre3.setText("Horas:");

        jLabelInfoNombre4.setText("Nombre del ciclo:");

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("CREAR MODULO");

        jButtonGuardar.setBackground(new java.awt.Color(75, 75, 75));
        jButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jTextFieldNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNombre.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNombre.setMinimumSize(new java.awt.Dimension(64, 128));
        jTextFieldNombre.setPreferredSize(new java.awt.Dimension(64, 128));
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jTextFieldCreditos.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCreditos.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCreditos.setMinimumSize(new java.awt.Dimension(64, 128));
        jTextFieldCreditos.setPreferredSize(new java.awt.Dimension(64, 128));
        jTextFieldCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCreditosActionPerformed(evt);
            }
        });

        jTextFieldHoras.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldHoras.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldHoras.setPreferredSize(new java.awt.Dimension(64, 128));

        jButtonCancelar.setBackground(new java.awt.Color(75, 75, 75));
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelCurso1.setText("Desde 0 hasta 99'99 ");

        jComboBoxCiclos.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxCiclos.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxCiclos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxCurso.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxCurso.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelInfoNombre4)
                                        .addGap(86, 86, 86))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelInfoCreditos, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelInfoCurso, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelInfoNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelInfoNombre3, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldHoras, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCreditos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCiclos, 0, 155, Short.MAX_VALUE)
                                    .addComponent(jComboBoxCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelCurso1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCancelar)
                                .addGap(33, 33, 33)
                                .addComponent(jButtonGuardar)))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInfoNombre))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInfoCurso)
                    .addComponent(jComboBoxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInfoCreditos)
                    .addComponent(jLabelCurso1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInfoNombre3)
                    .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInfoNombre4)
                    .addComponent(jComboBoxCiclos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jButtonCancelar))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCreditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCreditosActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres cancelar? Se perderá todo lo creado en este proceso.",
                "Cancelar creación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            GestionBaseDeDatos.cancelarTransaccion();
            this.dispose();
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        crearModulo();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    /**
     * Punto de entrada para pruebas aisladas del formulario.
     *
     * @param args Argumentos de línea de comandos (no utilizados).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearModulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearModulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearModulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearModulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CrearModulo().setVisible(true);
        });
    }

    /**
     * Pide confirmación y, si el usuario acepta, cancela la transacción activa
     * y cierra la ventana.
     */
    private void cancelar() {
        int opcion = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que quieres cancelar? Se perderá todo lo creado en este proceso.",
                "Cancelar creación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion == JOptionPane.YES_OPTION) {
            GestionBaseDeDatos.cancelarTransaccion();
            this.dispose();
        }
    }

    /**
     * Valida los campos, inserta el módulo en la BD y vuelve al formulario de
     * gestión de módulos del ciclo.
     */
    private void crearModulo() {

        String nombre = jTextFieldNombre.getText().trim();
        String curso = jComboBoxCurso.getSelectedItem().toString();
        String creditosTexto = jTextFieldCreditos.getText().trim();
        String horasTexto = jTextFieldHoras.getText().trim();

        if (!Validadores.validarTextoNoVacio(nombre)) {
            JOptionPane.showMessageDialog(this, "El nombre del módulo no puede estar vacío.");
            return;
        }
        if (!Validadores.validarTextoNoVacio(creditosTexto)) {
            JOptionPane.showMessageDialog(this, "Los créditos no pueden estar vacíos.");
            return;
        }
        if (!Validadores.validarTextoNoVacio(horasTexto)) {
            JOptionPane.showMessageDialog(this, "Las horas no pueden estar vacías.");
            return;
        }
        if (idCicloSeleccionado == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un ciclo.");
            return;
        }

        double creditos = 0;
        int horas = 0;

        try {
            creditos = Double.parseDouble(creditosTexto);
            horas = Integer.parseInt(horasTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Créditos y horas deben ser números.");
            return;
        }
        if (!Validadores.validarCurso(curso)) {
            JOptionPane.showMessageDialog(this, "El curso debe ser 1 o 2.");
            return;
        }
        if (!Validadores.validarCreditosEcts(creditos)) {
            JOptionPane.showMessageDialog(this, "Los créditos deben estar entre 0 y 99.99.");
            return;
        }
        if (!Validadores.validarHorasModulo(horas)) {
            JOptionPane.showMessageDialog(this, "Las horas deben ser mayores que 0.");
            return;
        }

        String[] datos = {
            nombre,
            curso,
            String.valueOf(creditos),
            String.valueOf(horas),
            String.valueOf(idCicloSeleccionado)
        };

        int idModulo = GestionBaseDeDatos.insertarYDevolverID(ConsultasSQL.INSERT_MODULO[1], datos);

        if (idModulo != -1) {
            JOptionPane.showMessageDialog(this, "Módulo creado correctamente con ID: " + idModulo);

            Modulo modulo = new Modulo(new String[]{
                String.valueOf(idModulo), String.valueOf(idCicloSeleccionado), nombre,
                curso, String.valueOf(creditos), String.valueOf(horas)
            });
            SesionDatos.registrarModulo(modulo, false);
            

        } else {
            JOptionPane.showMessageDialog(this, "Error al crear el módulo.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JComboBox<String> jComboBoxCiclos;
    private javax.swing.JComboBox<String> jComboBoxCurso;
    private javax.swing.JLabel jLabelCurso1;
    private javax.swing.JLabel jLabelInfoCreditos;
    private javax.swing.JLabel jLabelInfoCurso;
    private javax.swing.JLabel jLabelInfoNombre;
    private javax.swing.JLabel jLabelInfoNombre3;
    private javax.swing.JLabel jLabelInfoNombre4;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldCreditos;
    private javax.swing.JTextField jTextFieldHoras;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
