/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.debug;



import javax.swing.*;

import java.awt.*;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import servicios.BaseDeDatos.ConsultasSQL;
import servicios.BaseDeDatos.GestionBaseDeDatos;

/**
 * Ventana de depuración que muestra resultados de consultas SQL en una JTable.
 *
 * @author isard
 */
public class VisorTabla extends javax.swing.JFrame {

    /**
     * Creates new form VisorTabla
     */
    public VisorTabla() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visor de Tablas");
        setMinimumSize(new java.awt.Dimension(800, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
       /**
     * Devuelve la SQL SELECT correspondiente a cada tabla del proyecto.
     *
     * Usa los mismos arrays de ConsultasSQL para no duplicar código.
     *
     * @param tabla Nombre de la tabla.
     * @return SQL SELECT, o null si la tabla no se reconoce.
     */
    private String obtenerSqlParaTabla(String tabla) {
        return switch (tabla.toLowerCase()) {
            case "alumno" ->
                ConsultasSQL.SELECT_ALUMNO_TODOS[0];
            case "ciclo" ->
                ConsultasSQL.SELECT_CICLO_TODOS[0];
            case "modulo" ->
                ConsultasSQL.SELECT_MODULO_TODOS[0];
            case "matricula" ->
                ConsultasSQL.SELECT_MATRICULA_TODOS[0];
            case "linea_matricula" ->
                ConsultasSQL.SELECT_LINEA_MATRICULA_TODOS[0];
            default ->
                null;
        };
    }

    /**
     * Ventana reutilizable que muestra el contenido de cualquier tabla de la BD
     * en un JTable con ordenación por columnas y selección de fila.
     *
     * =====================================================================
     * CÓMO FUNCIONA (PATRÓN COMPLETO):
     * =====================================================================
     *
     * 1. GestionBaseDeDatos.obtenerTableModel(sql, params) → ejecuta el SELECT
     * en MySQL → lee los metadatos (nombres de columna) con ResultSetMetaData →
     * llena un DefaultTableModel con cabeceras + filas → devuelve el modelo
     * listo para usar
     *
     * 2. jTable.setModel(modelo) → conecta el modelo al JTable; la tabla se
     * actualiza al instante
     *
     * 3. {@code TableRowSorter<>(modelo)} → añade ordenación por clic en cabecera sin
     * cambiar los datos
     *
     * 4. jTable.getSelectedRow() / convertRowIndexToModel() → obtiene la fila
     * seleccionada y convierte el índice visual al real (necesario cuando la
     * tabla está ordenada)
     *
     * PARA AÑADIR ESTA PANTALLA A PantallaPrincipal:
     *
     *   // En el botón "Consultar" de PantallaPrincipal: String tabla =
     * jComboBoxTipoDato.getSelectedItem().toString(); new
     * VisorTabla(tabla).setVisible(true);
     *
     * =====================================================================
     */
    

        // ---- Componentes Swing ----
        private JTable jTable;
        private JScrollPane scrollPane;
        private JComboBox<String> comboTabla;
        private JButton btnRefrescar;
        private JButton btnCerrar;
        private JLabel lblSeleccion;
        private JLabel lblContador;

        // ---- Estado ----
        /**
         * Último índice de fila seleccionado EN EL MODELO (no en la vista).
         */
        private int filaSeleccionadaModelo = -1;

        // =========================================================
        // =================== CONSTRUCTOR =========================
        // =========================================================
        /**
         * Crea un visor de tablas.
         *
         * @param tablaInicial Nombre de la tabla a mostrar al abrirse
         * ("alumno", "ciclo", "modulo", "matricula" o "linea_matricula"). Puede
         * ser null para mostrar el combo vacío.
         */
        public VisorTabla(String tablaInicial) {
            super("Visor de Tablas — Base de Datos");
            construirInterfaz();
            configurarEventos();

            if (tablaInicial != null && !tablaInicial.isBlank()) {
                comboTabla.setSelectedItem(tablaInicial.toLowerCase());
                cargarTabla(tablaInicial.toLowerCase());
            }

            pack();
            setMinimumSize(new Dimension(750, 450));
            setLocationRelativeTo(null); // centrar en pantalla
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }

        // =========================================================
        // ================= CONSTRUCCIÓN UI =======================
        // =========================================================
        /**
         * Construye todos los componentes y el layout de la ventana. Se hace
         * manualmente (sin el diseñador de NetBeans) para que el código sea
         * completamente legible.
         */
        private void construirInterfaz() {

            // ---- Panel superior: combo + botones ----
            JPanel panelSuperior = new JPanel(new FlowLayout(FlowLayout.LEFT, 10, 8));
            panelSuperior.setBackground(new Color(45, 45, 48));

            JLabel lblTabla = new JLabel("Tabla:");
            lblTabla.setForeground(Color.WHITE);
            lblTabla.setFont(new Font("Segoe UI", Font.BOLD, 13));

            comboTabla = new JComboBox<>(new String[]{
                "alumno", "ciclo", "modulo", "matricula", "linea_matricula"
            });
            comboTabla.setFont(new Font("Segoe UI", Font.PLAIN, 13));
            comboTabla.setPreferredSize(new Dimension(160, 26));

            btnRefrescar = new JButton("⟳ Refrescar");
            estilizarBoton(btnRefrescar, new Color(0, 120, 212));

            btnCerrar = new JButton("✕ Cerrar");
            estilizarBoton(btnCerrar, new Color(180, 50, 50));

            panelSuperior.add(lblTabla);
            panelSuperior.add(comboTabla);
            panelSuperior.add(btnRefrescar);
            panelSuperior.add(btnCerrar);

            // ---- JTable dentro de un JScrollPane ----
            //
            // DefaultTableModel con isCellEditable=false → celdas de sólo lectura.
            // GestionBaseDeDatos.obtenerTableModel() ya devuelve este tipo de modelo,
            // pero aquí creamos uno vacío inicial para que el JTable esté listo.
            //
            jTable = new JTable(new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false; // No se puede editar directamente en la tabla
                }
            });

            // Aspecto visual de la tabla
            jTable.setFont(new Font("Segoe UI", Font.PLAIN, 13));
            jTable.setRowHeight(24);
            jTable.setGridColor(new Color(210, 210, 210));
            jTable.setSelectionBackground(new Color(0, 120, 212, 80));
            jTable.setSelectionForeground(Color.BLACK);
            jTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
            jTable.getTableHeader().setBackground(new Color(240, 240, 240));
            jTable.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);

            // Solo permite seleccionar una fila a la vez
            jTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

            scrollPane = new JScrollPane(jTable);
            scrollPane.setBorder(BorderFactory.createEmptyBorder(8, 8, 8, 8));

            // ---- Panel inferior: info de selección y contador ----
            JPanel panelInferior = new JPanel(new BorderLayout());
            panelInferior.setBackground(new Color(240, 240, 240));
            panelInferior.setBorder(BorderFactory.createEmptyBorder(4, 10, 4, 10));

            lblSeleccion = new JLabel("Haz clic en una fila para seleccionarla.");
            lblSeleccion.setFont(new Font("Segoe UI", Font.ITALIC, 12));

            lblContador = new JLabel("0 registros");
            lblContador.setFont(new Font("Segoe UI", Font.BOLD, 12));
            lblContador.setHorizontalAlignment(SwingConstants.RIGHT);

            panelInferior.add(lblSeleccion, BorderLayout.WEST);
            panelInferior.add(lblContador, BorderLayout.EAST);

            // ---- Layout principal ----
            getContentPane().setLayout(new BorderLayout());
            getContentPane().add(panelSuperior, BorderLayout.NORTH);
            getContentPane().add(scrollPane, BorderLayout.CENTER);
            getContentPane().add(panelInferior, BorderLayout.SOUTH);
        }

        /**
         * Aplica estilo uniforme a un JButton.
         *
         * @param btn Botón a estilizar.
         * @param color Color de fondo.
         */
        private void estilizarBoton(JButton btn, Color color) {
            btn.setBackground(color);
            btn.setForeground(Color.WHITE);
            btn.setFont(new Font("Segoe UI", Font.BOLD, 12));
            btn.setFocusPainted(false);
            btn.setBorderPainted(false);
            btn.setCursor(Cursor.getDefaultCursor().getPredefinedCursor(Cursor.HAND_CURSOR));
            btn.setPreferredSize(new Dimension(120, 28));
        }

        // =========================================================
        // ==================== EVENTOS ============================
        // =========================================================
        /**
         * Conecta los listeners de todos los componentes interactivos.
         */
        private void configurarEventos() {

            // Cambiar de tabla en el combo → recargar automáticamente
            comboTabla.addActionListener(e -> {
                String tablaElegida = (String) comboTabla.getSelectedItem();
                if (tablaElegida != null) {
                    cargarTabla(tablaElegida);
                }
            });

            // Botón refrescar → recargar la tabla actual
            btnRefrescar.addActionListener(e -> {
                String tablaElegida = (String) comboTabla.getSelectedItem();
                if (tablaElegida != null) {
                    cargarTabla(tablaElegida);
                }
            });

            // Botón cerrar → cerrar ventana
            btnCerrar.addActionListener(e -> dispose());

            // Clic en fila → mostrar info en la barra inferior
            // MouseAdapter es más cómodo que ListSelectionListener porque distingue
            // click simple de doble click.
            jTable.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    int filaVista = jTable.getSelectedRow();

                    if (filaVista == -1) {
                        return; // nada seleccionado
                    }

                    // IMPORTANTE: cuando la tabla está ordenada, el índice visual
                    // y el índice real del modelo son distintos.
                    // convertRowIndexToModel convierte de vista → modelo.
                    filaSeleccionadaModelo = jTable.convertRowIndexToModel(filaVista);

                    // Construir texto con los valores de la fila seleccionada
                    DefaultTableModel modelo = (DefaultTableModel) jTable.getModel();
                    StringBuilder sb = new StringBuilder("Seleccionado → ");
                    for (int col = 0; col < modelo.getColumnCount(); col++) {
                        sb.append(modelo.getColumnName(col))
                                .append(": ")
                                .append(modelo.getValueAt(filaSeleccionadaModelo, col))
                                .append("  ");
                    }
                    lblSeleccion.setText(sb.toString());

                    // Doble clic → abrir formulario de edición (ejemplo)
                    if (e.getClickCount() == 2) {
                        abrirFormularioEdicion();
                    }
                }
            });
        }

        // =========================================================
        // ================== CARGA DE DATOS =======================
        // =========================================================
        /**
         * Carga los datos de la tabla indicada y los muestra en el JTable.
         *
         * Este es el método central del patrón: BD → obtenerTableModel() →
         * jTable.setModel() → añadir sorter
         *
         * @param tabla Nombre de la tabla de la BD a mostrar.
         */
        private void cargarTabla(String tabla) {

            // 1. Obtener la SQL adecuada para la tabla elegida
            String sql = obtenerSqlParaTabla(tabla);
            if (sql == null) {
                JOptionPane.showMessageDialog(this,
                        "Tabla desconocida: " + tabla,
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 2. Ejecutar en BD y obtener el DefaultTableModel
            //    → GestionBaseDeDatos lee el ResultSet y construye el modelo
            DefaultTableModel modelo = GestionBaseDeDatos.obtenerTableModel(sql, new String[0]);

            // 3. Asignar el modelo al JTable — la tabla se actualiza al instante
            jTable.setModel(modelo);

            // 4. Añadir TableRowSorter para que se pueda ordenar haciendo clic
            //    en cualquier cabecera de columna (sin tocar los datos del modelo)
            TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(modelo);
            jTable.setRowSorter(sorter);

            // 5. Actualizar contador en la barra inferior
            int totalFilas = modelo.getRowCount();
            lblContador.setText(totalFilas + " registro" + (totalFilas != 1 ? "s" : ""));
            lblSeleccion.setText("Haz clic en una fila para seleccionarla.");
            filaSeleccionadaModelo = -1;

            setTitle("Visor — Tabla: " + tabla.toUpperCase() + " (" + totalFilas + " registros)");
        }

        

        // =========================================================
        // ============ INTEGRACIÓN CON FORMULARIOS ================
        // =========================================================
        /**
         * Se llama al hacer doble clic en una fila. Recupera el código de la
         * primera columna y abre el formulario de edición.
         *
         * Adapta este método a tus formularios (ModificarAlumno, CrearCiclo,
         * etc.)
         */
        private void abrirFormularioEdicion() {
            if (filaSeleccionadaModelo == -1) {
                return;
            }

            DefaultTableModel modelo = (DefaultTableModel) jTable.getModel();

            // La primera columna siempre es "codigo" en todas las tablas del proyecto
            Object valorCodigo = modelo.getValueAt(filaSeleccionadaModelo, 0);
            String tablaActual = (String) comboTabla.getSelectedItem();

            JOptionPane.showMessageDialog(this,
                    "Doble clic detectado.\n"
                    + "Tabla: " + tablaActual + "\n"
                    + "Código seleccionado: " + valorCodigo + "\n\n"
                    + "Aquí abrirías el formulario de modificación.\n"
                    + "Ejemplo:\n"
                    + "  new ModificarAlumno(ModoFormulario.MODIFICAR, alumno).setVisible(true);",
                    "Editar registro",
                    JOptionPane.INFORMATION_MESSAGE
            );

            // EJEMPLO REAL para Alumno (descomentar cuando esté listo):
            //
            // if ("alumno".equals(tablaActual)) {
            //     int codigo = Integer.parseInt(valorCodigo.toString());
            //     Alumno alumno = buscarAlumnoPorCodigo(codigo); // buscar en listaAlumno
            //     new ModificarAlumno(ModoFormulario.MODIFICAR, alumno).setVisible(true);
            // }
        }

        /**
         * Devuelve el valor de la columna de la fila actualmente seleccionada.
         * Útil para que la pantalla padre recupere el código al cerrar esta
         * ventana.
         *
         * @param columna Índice de la columna (0 = código).
         * @return Valor como String, o null si no hay selección.
         */
        public String getValorSeleccionado(int columna) {
            if (filaSeleccionadaModelo == -1) {
                return null;
            }
            Object valor = ((DefaultTableModel) jTable.getModel())
                    .getValueAt(filaSeleccionadaModelo, columna);
            return valor != null ? valor.toString() : null;
        }

        // =========================================================
        // =================== MAIN DE PRUEBA ======================
        // =========================================================
        /**
         * Punto de entrada rápido para probar el visor de forma independiente.
         * En el proyecto real se lanza desde PantallaPrincipal.
         *
         * @param args No se usa.
         */
        public static void main(String[] args) {
            try {
                UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (Exception ignored) {
            }

            java.awt.EventQueue.invokeLater(() -> {
                GestionBaseDeDatos.vincularBDD();
                new VisorTabla("alumno").setVisible(true);
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

