/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Modificar;

import Control.SesionDatos;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelos.Ciclo;
import modelos.Modulo;
import servicios.BaseDeDatos.ConsultasSQL;
import servicios.BaseDeDatos.GestionBaseDeDatos;

/**
 * Ventana principal del módulo de modificación. Muestra botones para abrir
 * el formulario de cada entidad (Alumno, Ciclo, Módulo, Matrícula, LineaMatrícula).
 *
 * @author rich
 */
public class Menu_Modificar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu_Modificar.class.getName());

    /**
     * Inicializa el menú de modificación, registra los listeners de los botones
     * Alumno y Matrícula, y precarga ciclos y módulos en sesión si las listas están vacías.
     */
    public Menu_Modificar() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jButtonAlumno.addActionListener(e -> abrirModificarAlumno());
        jButtonMatricula.addActionListener(e -> abrirModificarMatricula());
        cargarDatosSesion();
    }

    //** Precarga en sesión los ciclos y módulos desde la BD si las listas están vacías. */
    private void cargarDatosSesion() {
        if (SesionDatos.getListaCiclos().isEmpty()) {
            GestionBaseDeDatos.realizarConsultaSQL(ConsultasSQL.SAVE_CICLO_TODOS, new String[0], false, true);
        }
        if (SesionDatos.getListaModulos().isEmpty()) {
            GestionBaseDeDatos.realizarConsultaSQL(ConsultasSQL.SAVE_MODULO_TODOS, new String[0], false, true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAlumno = new javax.swing.JButton();
        jButtonMatricula = new javax.swing.JButton();
        jButtonLineaMatricula = new javax.swing.JButton();
        jButtonModulo = new javax.swing.JButton();
        jButtonCiclo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAlumno.setText("Alumno");

        jButtonMatricula.setText("Matricula");

        jButtonLineaMatricula.setText("LineaMatricula");
        jButtonLineaMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLineaMatriculaActionPerformed(evt);
            }
        });

        jButtonModulo.setText("Modulo");
        jButtonModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModuloActionPerformed(evt);
            }
        });

        jButtonCiclo.setText("Ciclo");
        jButtonCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCicloActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("MODIFICAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(423, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAlumno)
                        .addGap(29, 29, 29)
                        .addComponent(jButtonMatricula)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonLineaMatricula)
                        .addGap(31, 31, 31)
                        .addComponent(jButtonModulo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCiclo)
                        .addGap(404, 404, 404))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(520, 520, 520))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlumno)
                    .addComponent(jButtonMatricula)
                    .addComponent(jButtonLineaMatricula)
                    .addComponent(jButtonModulo)
                    .addComponent(jButtonCiclo))
                .addContainerGap(472, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLineaMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLineaMatriculaActionPerformed
        abrirModificarLineaMatricula();
    }//GEN-LAST:event_jButtonLineaMatriculaActionPerformed

    private void jButtonModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModuloActionPerformed
        abrirModificarModulo();
    }//GEN-LAST:event_jButtonModuloActionPerformed

    private void jButtonCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCicloActionPerformed
        abrirModificarCiclo();
    }//GEN-LAST:event_jButtonCicloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu_Modificar().setVisible(true));
    }

    /** Abre el formulario de modificación de alumnos. */
    public void abrirModificarAlumno() {
        new ModificarAlumno().setVisible(true);
    }

    /**
     * Muestra un diálogo de selección con los ciclos disponibles en sesión
     * y abre el formulario de modificación para el ciclo elegido.
     */
    public void abrirModificarCiclo() {
        ArrayList<Ciclo> lista = new ArrayList<>(SesionDatos.getListaCiclos());
        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay ciclos cargados en sesión.");
            return;
        }
        String[] opciones = new String[lista.size()];
        for (int i = 0; i < lista.size(); i++) {
            opciones[i] = lista.get(i).getCodigo() + " - " + lista.get(i).getDenominacion();
        }
        String sel = (String) JOptionPane.showInputDialog(this,
            "Selecciona el ciclo a modificar:", "Modificar ciclo",
            JOptionPane.PLAIN_MESSAGE, null, opciones, opciones[0]);
        if (sel == null) return;
        for (Ciclo c : lista) {
            if ((c.getCodigo() + " - " + c.getDenominacion()).equals(sel)) {
                new ModificarCiclo(c).setVisible(true);
                break;
            }
        }
    }

    /**
     * Muestra un diálogo de selección con los módulos disponibles en sesión
     * y abre el formulario de modificación para el módulo elegido.
     */
    public void abrirModificarModulo() {
        ArrayList<Modulo> lista = new ArrayList<>(SesionDatos.getListaModulos());
        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay módulos cargados en sesión.");
            return;
        }
        String[] opciones = new String[lista.size()];
        for (int i = 0; i < lista.size(); i++) {
            opciones[i] = lista.get(i).getCodigo() + " - " + lista.get(i).getNombre();
        }
        String sel = (String) JOptionPane.showInputDialog(this,
            "Selecciona el módulo a modificar:", "Modificar módulo",
            JOptionPane.PLAIN_MESSAGE, null, opciones, opciones[0]);
        if (sel == null) return;
        for (Modulo m : lista) {
            if ((m.getCodigo() + " - " + m.getNombre()).equals(sel)) {
                new ModificarModulo(m).setVisible(true);
                break;
            }
        }
    }

    /** Abre el formulario de modificación de matrículas. */
    public void abrirModificarMatricula() {
        new ModificarMatricula().setVisible(true);
    }

    /** Abre el formulario de modificación de líneas de matrícula. */
    public void abrirModificarLineaMatricula() {
        new ModificarLineaMatricula().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlumno;
    private javax.swing.JButton jButtonCiclo;
    private javax.swing.JButton jButtonLineaMatricula;
    private javax.swing.JButton jButtonMatricula;
    private javax.swing.JButton jButtonModulo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
