/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Modificar;

import Control.SesionDatos;
import Utils.Validadores;
import excepciones.Alumno.AlumnoVacioException;
import excepciones.Alumno.CorreoNoValidoException;
import excepciones.Alumno.DomicilioVacioException;
import excepciones.Alumno.TelefonoInvalidoException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Alumno;
import servicios.BaseDeDatos.ConsultasSQL;
import servicios.BaseDeDatos.GestionBaseDeDatos;

/**
 * Formulario Swing para consultar y modificar los datos de un alumno existente.
 * Muestra la lista completa de alumnos en una tabla y carga el seleccionado en
 * los campos de edición.
 *
 * @author Rich
 */
public class ModificarAlumno extends javax.swing.JFrame {

    Alumno alumno;
    private DefaultTableModel modeloTabla;

    /**
     * Abre el formulario de modificación de alumnos, carga la tabla con todos
     * los alumnos de la BD y bloquea la fecha de nacimiento para que no sea editable.
     */
    public ModificarAlumno() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jTextFieldFechaNacimiento.setEditable(false);
        jTextFieldFechaNacimiento.setFocusable(false);

        configurarTabla();
        cargarAlumnosEnTabla();
    }

    /**
     * Inicializa el modelo de la tabla con columnas no editables y registra el
     * listener de selección.
     */
    private void configurarTabla() {
        modeloTabla = new DefaultTableModel(
                new Object[]{"Código", "Nombre", "Correo", "Fecha nacimiento", "Domicilio", "Teléfono"},
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        jTable1.setModel(modeloTabla);

        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                cargarAlumnoSeleccionado();
            }
        });
    }

    /**
     * Consulta todos los alumnos de la BD ordenados por nombre y los muestra en
     * la tabla.
     */
    private void cargarAlumnosEnTabla() {
        modeloTabla.setRowCount(0);
        String sql = "SELECT codigo, nombre, correo, fecha_nacimiento, domicilio, telefono FROM alumno ORDER BY nombre ASC";
        DefaultTableModel temp = GestionBaseDeDatos.obtenerTableModel(sql, new String[0]);
        for (int i = 0; i < temp.getRowCount(); i++) {
            modeloTabla.addRow(new Object[]{
                temp.getValueAt(i, 0),
                temp.getValueAt(i, 1),
                temp.getValueAt(i, 2),
                temp.getValueAt(i, 3),
                temp.getValueAt(i, 4),
                temp.getValueAt(i, 5)
            });
        }
    }

    /**
     * Lee la fila seleccionada en la tabla, construye el objeto Alumno y
     * rellena los campos del formulario. Los campos nulos en BD se muestran vacíos.
     */
    private void cargarAlumnoSeleccionado() {
        int fila = jTable1.getSelectedRow();
        if (fila == -1) {
            return;
        }

        // Table columns: 0=codigo, 1=nombre, 2=correo, 3=fecha_nacimiento, 4=domicilio, 5=telefono
        // Alumno(String[]) expects: 0=codigo, 1=nombre, 2=fecha_nacimiento, 3=domicilio, 4=telefono, 5=correo
        String[] datos = {
            celda(fila, 0),
            celda(fila, 1),
            celda(fila, 3),
            celda(fila, 4),
            celda(fila, 5),
            celda(fila, 2)
        };
        alumno = new Alumno(datos);

        jTextFieldNombre.setText(alumno.getNombre() != null ? alumno.getNombre() : "");
        jTextFieldCorreo.setText(alumno.getCorreo() != null ? alumno.getCorreo() : "");
        jTextFieldFechaNacimiento.setText(alumno.getFechaNacimiento() != null ? alumno.getFechaNacimiento().toString() : "");
        jTextFieldDomicilio.setText(alumno.getDomicilio() != null ? alumno.getDomicilio() : "");
        jTextFieldTelefono.setText(alumno.getTelefono() != null ? alumno.getTelefono() : "");
    }

    /** Devuelve el valor de la celda como String, o "" si es null. */
    private String celda(int fila, int col) {
        Object val = modeloTabla.getValueAt(fila, col);
        return val != null ? val.toString() : "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonGuardar = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldDomicilio = new javax.swing.JTextField();
        jTextFieldFechaNacimiento = new javax.swing.JTextField();
        jLabelInfoNombre = new javax.swing.JLabel();
        jLabelInfoNombre2 = new javax.swing.JLabel();
        jLabelInfoNombre3 = new javax.swing.JLabel();
        jLabelInfoNombre4 = new javax.swing.JLabel();
        jLabelInfoNombre5 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelInfoNombre6 = new javax.swing.JLabel();
        jLabelInfoNombre7 = new javax.swing.JLabel();
        jLabelInfoNombre8 = new javax.swing.JLabel();
        jLabelInfoNombre9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonGuardar.setBackground(new java.awt.Color(75, 75, 75));
        jButtonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jTextFieldNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNombre.setMinimumSize(new java.awt.Dimension(64, 128));
        jTextFieldNombre.setPreferredSize(new java.awt.Dimension(64, 128));
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jTextFieldCorreo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCorreo.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCorreo.setMinimumSize(new java.awt.Dimension(64, 128));
        jTextFieldCorreo.setPreferredSize(new java.awt.Dimension(64, 128));
        jTextFieldCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCorreoActionPerformed(evt);
            }
        });

        jTextFieldTelefono.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTelefono.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldTelefono.setPreferredSize(new java.awt.Dimension(64, 128));

        jTextFieldDomicilio.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldDomicilio.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldDomicilio.setPreferredSize(new java.awt.Dimension(64, 128));

        jTextFieldFechaNacimiento.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldFechaNacimiento.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldFechaNacimiento.setPreferredSize(new java.awt.Dimension(64, 128));

        jLabelInfoNombre.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInfoNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInfoNombre.setText("Nombre:");

        jLabelInfoNombre2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInfoNombre2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInfoNombre2.setText("Correo:");

        jLabelInfoNombre3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInfoNombre3.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInfoNombre3.setText("F:/ Nacimiento");

        jLabelInfoNombre4.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInfoNombre4.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInfoNombre4.setText("Domicilio:");

        jLabelInfoNombre5.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInfoNombre5.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInfoNombre5.setText("Telefono:");

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("NSimSun", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("MODIFICAR ALUMNADO");

        jButtonCancelar.setBackground(new java.awt.Color(75, 75, 75));
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabelInfoNombre6.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInfoNombre6.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInfoNombre6.setText("Ej: 2002-03-13");

        jLabelInfoNombre7.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInfoNombre7.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInfoNombre7.setText("Ej: Avenida Santa Isabel 18, Zaragoza, Zaragoza");

        jLabelInfoNombre8.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInfoNombre8.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInfoNombre8.setText("Ej: 123456789");

        jLabelInfoNombre9.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInfoNombre9.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInfoNombre9.setText("Ej: Alguien@Direccion.com");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGuardar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelInfoNombre2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelInfoNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelInfoNombre3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelInfoNombre5)
                                .addComponent(jLabelInfoNombre4)))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInfoNombre6)
                    .addComponent(jLabelInfoNombre7)
                    .addComponent(jLabelInfoNombre8)
                    .addComponent(jLabelInfoNombre9))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelInfoNombre))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelInfoNombre2)
                            .addComponent(jLabelInfoNombre9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelInfoNombre3)
                            .addComponent(jLabelInfoNombre6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelInfoNombre4)
                            .addComponent(jLabelInfoNombre7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelInfoNombre8))
                            .addComponent(jLabelInfoNombre5))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCancelar)
                            .addComponent(jButtonGuardar))))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        modificarAlumno();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jTextFieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        GestionBaseDeDatos.cancelarTransaccion();
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ModificarAlumno().setVisible(true);
        });
    }

    /**
     * Valida los campos editados, actualiza el objeto Alumno y persiste los
     * cambios en la BD.
     */
    private void modificarAlumno() {
        try {
            if (alumno == null) {
                JOptionPane.showMessageDialog(this, "Selecciona un alumno de la tabla primero.");
                return;
            }
            
            String nombre = jTextFieldNombre.getText().trim();
            String correo = jTextFieldCorreo.getText().trim();
            String domicilio = jTextFieldDomicilio.getText().trim();
            String telefono = jTextFieldTelefono.getText().trim();
            
            if (nombre.isBlank()) {
                JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío.");
                return;
            }
            if (!Validadores.validarCorreo(correo)) {
                JOptionPane.showMessageDialog(this, "El correo no tiene un formato válido (usuario@dominio.ext).");
                return;
            }
            if (!Validadores.validarDireccion(domicilio)) {
                JOptionPane.showMessageDialog(this, """
                                                    El domicilio debe tener el formato: TipoV\u00eda Nombre N\u00famero, Localidad, Provincia
                                                    Ejemplo: Calle Mayor 5, Madrid, Madrid""");
                return;
            }
            if (!Validadores.validarTelefono(telefono)) {
                JOptionPane.showMessageDialog(this, "El teléfono debe tener exactamente 9 dígitos numéricos.");
                return;
            }
            
            alumno.setNombre(nombre);
            alumno.setCorreo(correo);
            alumno.setDomicilio(domicilio);
            alumno.setTelefono(telefono);
            
            // UPDATE_ALUMNO: nombre, fecha_nacimiento, domicilio, telefono, correo, codigo
            String[] entradas = {
                alumno.getNombre(),
                alumno.getFechaNacimiento().toString(),
                alumno.getDomicilio(),
                alumno.getTelefono(),
                alumno.getCorreo(),
                String.valueOf(alumno.getCodigo())
            };
            GestionBaseDeDatos.actualizarFila(ConsultasSQL.UPDATE_ALUMNO, entradas);
            
            int codigoAlumno = alumno.getCodigo();
            SesionDatos.getListaAlumnos().removeIf(a -> a.getCodigo() == codigoAlumno);
            SesionDatos.getListaAlumnos().add(alumno);
            
            JOptionPane.showMessageDialog(this, "Alumno modificado correctamente.");
            alumno = null;
            cargarAlumnosEnTabla();
        } catch (AlumnoVacioException | CorreoNoValidoException | DomicilioVacioException | TelefonoInvalidoException ex) {
            System.getLogger(ModificarAlumno.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jLabelInfoNombre;
    private javax.swing.JLabel jLabelInfoNombre2;
    private javax.swing.JLabel jLabelInfoNombre3;
    private javax.swing.JLabel jLabelInfoNombre4;
    private javax.swing.JLabel jLabelInfoNombre5;
    private javax.swing.JLabel jLabelInfoNombre6;
    private javax.swing.JLabel jLabelInfoNombre7;
    private javax.swing.JLabel jLabelInfoNombre8;
    private javax.swing.JLabel jLabelInfoNombre9;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldDomicilio;
    private javax.swing.JTextField jTextFieldFechaNacimiento;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
