/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Modificar;

import Utils.Validadores;
import javax.swing.JOptionPane;
import modelos.Modulo;
import servicios.BaseDeDatos.ConsultasSQL;
import servicios.BaseDeDatos.GestionBaseDeDatos;

/**
 * Formulario Swing para modificar un módulo formativo existente.
 * Recibe el módulo a editar en el constructor y carga sus datos automáticamente.
 *
 * @author Rich
 */
public class ModificarModulo extends javax.swing.JFrame {

    private Modulo modulo;
    /**
     * Creates new form FormularioModul
     */
    public ModificarModulo() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonGuardar1 = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCurso = new javax.swing.JTextField();
        jTextFieldCreditos = new javax.swing.JTextField();
        jTextFieldCod_Ciclo = new javax.swing.JTextField();
        jLabelInfoNombre = new javax.swing.JLabel();
        jTextFieldHoras = new javax.swing.JTextField();
        jLabelInfoCurso = new javax.swing.JLabel();
        jLabelInfoCreditos = new javax.swing.JLabel();
        jLabelCurso = new javax.swing.JLabel();
        jLabelInfoNombre3 = new javax.swing.JLabel();
        jLabelCurso1 = new javax.swing.JLabel();
        jLabelInfoNombre4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelTitulo.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("MODIFICAR MODULO");

        jButtonGuardar1.setText("Guardar");
        jButtonGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardar1ActionPerformed(evt);
            }
        });

        jTextFieldNombre.setMinimumSize(new java.awt.Dimension(64, 128));
        jTextFieldNombre.setPreferredSize(new java.awt.Dimension(64, 128));
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jTextFieldCurso.setMinimumSize(new java.awt.Dimension(64, 128));
        jTextFieldCurso.setPreferredSize(new java.awt.Dimension(64, 128));

        jTextFieldCreditos.setMinimumSize(new java.awt.Dimension(64, 128));
        jTextFieldCreditos.setPreferredSize(new java.awt.Dimension(64, 128));
        jTextFieldCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCreditosActionPerformed(evt);
            }
        });

        jTextFieldCod_Ciclo.setPreferredSize(new java.awt.Dimension(64, 128));

        jLabelInfoNombre.setText("Nombre:");

        jTextFieldHoras.setPreferredSize(new java.awt.Dimension(64, 128));

        jLabelInfoCurso.setText("Curso:");

        jLabelInfoCreditos.setText("Creditos");

        jLabelCurso.setText("1 o 2");

        jLabelInfoNombre3.setText("Horas:");

        jLabelCurso1.setText("Desde 0 hasta 99'99 ");

        jLabelInfoNombre4.setText("Codigo del Ciclo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(387, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(382, 382, 382))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelInfoNombre4)
                                        .addGap(86, 86, 86))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabelInfoCreditos, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelInfoCurso, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelInfoNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelInfoNombre3, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelCurso))
                                    .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextFieldCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabelCurso1))
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCod_Ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jButtonCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonGuardar1)))
                        .addGap(357, 357, 357))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInfoNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInfoCurso)
                    .addComponent(jLabelCurso))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInfoCreditos)
                    .addComponent(jLabelCurso1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInfoNombre3)
                    .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInfoNombre4)
                    .addComponent(jTextFieldCod_Ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar1)
                    .addComponent(jButtonCancelar))
                .addContainerGap(328, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardar1ActionPerformed
        modificarModulo();
    }//GEN-LAST:event_jButtonGuardar1ActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCreditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCreditosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarModulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarModulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarModulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarModulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ModificarModulo().setVisible(true);
        });
    }
    
    /**
     * Abre el formulario con los datos del módulo preseleccionado cargados.
     *
     * @param modulo Módulo a modificar.
     */
    public ModificarModulo(Modulo modulo) {
        initComponents();
        this.modulo = modulo;
        setLocationRelativeTo(null);
        setTitle("Modificar Modulo");
        jButtonGuardar1.setText("Modificar Modulo");
        if (modulo != null) {
            cargarDatosModulo();
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún módulo.");
        }
    }

    /** Valida los campos del formulario y actualiza el módulo actual en la base de datos. */
    private void modificarModulo() {
       String nombre = jTextFieldNombre.getText();
        String curso = jTextFieldCurso.getText();
        String creditos = jTextFieldCreditos.getText();
        String horas = jTextFieldHoras.getText();
        String codigo_ciclo = jTextFieldCod_Ciclo.getText();

        if (Validadores.validarTextoNoVacio(nombre)|| Validadores.validarTextoNoVacio(curso) || Validadores.validarTextoNoVacio(creditos)
                || Validadores.validarTextoNoVacio(horas) || Validadores.validarTextoNoVacio(codigo_ciclo)) {
            JOptionPane.showMessageDialog(this, "Debes rellenar todos los campos.");
            return;
        }
        int cod_ciclo= Integer.parseInt(codigo_ciclo);
        int credits = Integer.parseInt(creditos);
        int hors = Integer.parseInt(horas);

        modulo.setNombre(nombre);
        modulo.setCurso(curso);
        modulo.setCreditos_ects(credits);
        modulo.setHoras(hors);
        modulo.setCodigo_ciclo(cod_ciclo);

        String[] entradas = {
            String.valueOf(modulo.getCodigo_ciclo()),
            modulo.getNombre(),
            modulo.getCurso(),
            String.valueOf(modulo.getCreditos_ects()),
            String.valueOf(modulo.getHoras()),
            String.valueOf(modulo.getCodigo())
        };
        GestionBaseDeDatos.actualizarFila(ConsultasSQL.UPDATE_MODULO, entradas);
        JOptionPane.showMessageDialog(this, "Modulo actualizado correctamente.");
        dispose();
    }
    
    /** Vuelca los datos del módulo asignado en los campos de texto del formulario. */
    private void cargarDatosModulo(){
        String creditos = String.valueOf(modulo.getCreditos_ects());
        String horas = String.valueOf(modulo.getHoras());
        String codigo_ciclo = String.valueOf(modulo.getCodigo_ciclo());
        
        jTextFieldNombre.setText(modulo.getNombre());
        jTextFieldCurso.setText(modulo.getCurso());
        jTextFieldCreditos.setText(creditos);
        jTextFieldCod_Ciclo.setText(codigo_ciclo);
        jTextFieldHoras.setText(horas);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar1;
    private javax.swing.JLabel jLabelCurso;
    private javax.swing.JLabel jLabelCurso1;
    private javax.swing.JLabel jLabelInfoCreditos;
    private javax.swing.JLabel jLabelInfoCurso;
    private javax.swing.JLabel jLabelInfoNombre;
    private javax.swing.JLabel jLabelInfoNombre3;
    private javax.swing.JLabel jLabelInfoNombre4;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldCod_Ciclo;
    private javax.swing.JTextField jTextFieldCreditos;
    private javax.swing.JTextField jTextFieldCurso;
    private javax.swing.JTextField jTextFieldHoras;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
