/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Modificar;

import Control.SesionDatos;
import Utils.Validadores;
import excepciones.Alumno.CodigMayor0Exception;
import excepciones.Ciclo.HorasMayor0Exception;
import excepciones.Modulo.CreditosMayor0Exception;
import excepciones.Modulo.CursoVacioException;
import excepciones.Modulo.NombreVacioException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelos.Modulo;
import servicios.BaseDeDatos.ConsultasSQL;
import servicios.BaseDeDatos.GestionBaseDeDatos;

/**
 * Formulario Swing para modificar un módulo formativo existente.
 * Recibe el módulo a editar en el constructor y carga sus datos automáticamente.
 *
 * @author Rich
 */
public class ModificarModulo extends javax.swing.JFrame {

    private Modulo modulo;
    /**
     * Creates new form FormularioModul
     */
    /**
     * Abre el formulario vacío de modificación de módulos sin ningún módulo preseleccionado.
     * El campo código de ciclo se bloquea para impedir reasignaciones de ciclo desde este formulario.
     */
    public ModificarModulo() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jTextFieldCod_Ciclo.setEditable(false);
        jComboBoxCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1", "2"}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonGuardar1 = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCreditos = new javax.swing.JTextField();
        jTextFieldCod_Ciclo = new javax.swing.JTextField();
        jLabelInfoNombre = new javax.swing.JLabel();
        jTextFieldHoras = new javax.swing.JTextField();
        jLabelInfoCurso = new javax.swing.JLabel();
        jLabelInfoCreditos = new javax.swing.JLabel();
        jLabelInfoNombre3 = new javax.swing.JLabel();
        jLabelCurso1 = new javax.swing.JLabel();
        jLabelInfoNombre4 = new javax.swing.JLabel();
        jComboBoxCurso = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCancelar.setBackground(new java.awt.Color(75, 75, 75));
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("NSimSun", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setText("MODIFICAR MODULO");

        jButtonGuardar1.setBackground(new java.awt.Color(75, 75, 75));
        jButtonGuardar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGuardar1.setText("Guardar");
        jButtonGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardar1ActionPerformed(evt);
            }
        });

        jTextFieldNombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNombre.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNombre.setMinimumSize(new java.awt.Dimension(64, 128));
        jTextFieldNombre.setPreferredSize(new java.awt.Dimension(64, 128));
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jTextFieldCreditos.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCreditos.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCreditos.setMinimumSize(new java.awt.Dimension(64, 128));
        jTextFieldCreditos.setPreferredSize(new java.awt.Dimension(64, 128));
        jTextFieldCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCreditosActionPerformed(evt);
            }
        });

        jTextFieldCod_Ciclo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCod_Ciclo.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldCod_Ciclo.setPreferredSize(new java.awt.Dimension(64, 128));

        jLabelInfoNombre.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInfoNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInfoNombre.setText("Nombre:");

        jTextFieldHoras.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldHoras.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldHoras.setPreferredSize(new java.awt.Dimension(64, 128));

        jLabelInfoCurso.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInfoCurso.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInfoCurso.setText("Curso:");

        jLabelInfoCreditos.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInfoCreditos.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInfoCreditos.setText("Creditos");

        jLabelInfoNombre3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInfoNombre3.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInfoNombre3.setText("Horas:");

        jLabelCurso1.setText("Desde 0 hasta 99'99 ");

        jLabelInfoNombre4.setBackground(new java.awt.Color(255, 255, 255));
        jLabelInfoNombre4.setForeground(new java.awt.Color(0, 0, 0));
        jLabelInfoNombre4.setText("Codigo del Ciclo:");

        jComboBoxCurso.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxCurso.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelInfoNombre4)
                                .addGap(86, 86, 86))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelInfoCreditos, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelInfoCurso, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelInfoNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelInfoNombre3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCurso1))
                            .addComponent(jTextFieldCod_Ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBoxCurso, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGuardar1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInfoNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInfoCurso)
                    .addComponent(jComboBoxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelInfoCreditos)
                    .addComponent(jLabelCurso1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInfoNombre3)
                    .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelInfoNombre4)
                    .addComponent(jTextFieldCod_Ciclo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar1)
                    .addComponent(jButtonCancelar))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardar1ActionPerformed
        try {
            modificarModulo();
        } catch (NombreVacioException | CursoVacioException | CreditosMayor0Exception | HorasMayor0Exception | CodigMayor0Exception ex) {
            Logger.getLogger(ModificarModulo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonGuardar1ActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCreditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCreditosActionPerformed

    /**
     * Punto de entrada para pruebas aisladas del formulario.
     *
     * @param args Argumentos de línea de comandos (no utilizados).
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarModulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarModulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarModulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarModulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ModificarModulo().setVisible(true);
        });
    }
    
    /**
     * Abre el formulario con los datos del módulo preseleccionado cargados.
     *
     * @param modulo Módulo a modificar.
     */
    public ModificarModulo(Modulo modulo) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.modulo = modulo;
        setLocationRelativeTo(null);
        setTitle("Modificar Modulo");
        jButtonGuardar1.setText("Modificar Modulo");
        jTextFieldCod_Ciclo.setEditable(false);
        jComboBoxCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"1", "2"}));
        if (modulo != null) {
            cargarDatosModulo();
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún módulo.");
        }
    }

    /** Valida los campos del formulario y actualiza el módulo actual en la base de datos. */
    private void modificarModulo() throws NombreVacioException, CursoVacioException, CreditosMayor0Exception, HorasMayor0Exception, CodigMayor0Exception {
        String nombre = jTextFieldNombre.getText().trim();
        String curso = jComboBoxCurso.getSelectedItem().toString();
        String creditos = jTextFieldCreditos.getText().trim();
        String horas = jTextFieldHoras.getText().trim();
        String codigo_ciclo = jTextFieldCod_Ciclo.getText().trim();

        if (nombre.isBlank()) {
            JOptionPane.showMessageDialog(this, "El nombre del módulo no puede estar vacío.");
            return;
        }
        if (creditos.isBlank()) {
            JOptionPane.showMessageDialog(this, "Los créditos no pueden estar vacíos.");
            return;
        }
        if (horas.isBlank()) {
            JOptionPane.showMessageDialog(this, "Las horas no pueden estar vacías.");
            return;
        }
        if (codigo_ciclo.isBlank()) {
            JOptionPane.showMessageDialog(this, "El código del ciclo no puede estar vacío.");
            return;
        }

        int cod_ciclo;
        double credits;
        int hors;
        try {
            cod_ciclo = Integer.parseInt(codigo_ciclo);
            credits = Double.parseDouble(creditos.replace(",", "."));
            hors = Integer.parseInt(horas);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Créditos y horas deben ser números.");
            return;
        }
        if (!Validadores.validarCurso(curso)) {
            JOptionPane.showMessageDialog(this, "El curso debe ser 1 o 2.");
            return;
        }
        if (!Validadores.validarCreditosEcts(credits)) {
            JOptionPane.showMessageDialog(this, "Los créditos deben estar entre 0 y 99.99.");
            return;
        }
        if (!Validadores.validarHorasModulo(hors)) {
            JOptionPane.showMessageDialog(this, "Las horas deben ser mayores que 0.");
            return;
        }

        try {
            modulo.setNombre(nombre);
            modulo.setCurso(curso);
            modulo.setCreditos_ects(credits);
            modulo.setHoras(hors);
            modulo.setCodigo_ciclo(cod_ciclo);
        } catch (NombreVacioException | CursoVacioException | CreditosMayor0Exception
                | HorasMayor0Exception | CodigMayor0Exception e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar los datos: " + e.getMessage());
            return;
        }

        String[] entradas = {
            String.valueOf(modulo.getCodigo_ciclo()),
            modulo.getNombre(),
            modulo.getCurso(),
            String.valueOf(modulo.getCreditos_ects()),
            String.valueOf(modulo.getHoras()),
            String.valueOf(modulo.getCodigo())
        };
        GestionBaseDeDatos.actualizarFila(ConsultasSQL.UPDATE_MODULO, entradas);

        int codigoModulo = modulo.getCodigo();
        SesionDatos.getListaModulos().removeIf(m -> m.getCodigo() == codigoModulo);
        SesionDatos.getListaModulos().add(modulo);

        JOptionPane.showMessageDialog(this, "Modulo actualizado correctamente.");
        dispose();
    }
    
    /** Vuelca los datos del módulo asignado en los campos de texto del formulario. */
    private void cargarDatosModulo(){
        String creditos = String.valueOf(modulo.getCreditos_ects());
        String horas = String.valueOf(modulo.getHoras());
        String codigo_ciclo = String.valueOf(modulo.getCodigo_ciclo());

        jTextFieldNombre.setText(modulo.getNombre());
        jComboBoxCurso.setSelectedItem(modulo.getCurso());
        jTextFieldCreditos.setText(creditos);
        jTextFieldCod_Ciclo.setText(codigo_ciclo);
        jTextFieldHoras.setText(horas);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar1;
    private javax.swing.JComboBox<String> jComboBoxCurso;
    private javax.swing.JLabel jLabelCurso1;
    private javax.swing.JLabel jLabelInfoCreditos;
    private javax.swing.JLabel jLabelInfoCurso;
    private javax.swing.JLabel jLabelInfoNombre;
    private javax.swing.JLabel jLabelInfoNombre3;
    private javax.swing.JLabel jLabelInfoNombre4;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldCod_Ciclo;
    private javax.swing.JTextField jTextFieldCreditos;
    private javax.swing.JTextField jTextFieldHoras;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
