/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

/**
 *
 * @author 1DAM
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private boolean bdImportada = false;

    /**
     * Creates new form Pantalla
     */
    public PantallaPrincipal() {
        initComponents();
        actualizarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jButtonImportar = new javax.swing.JButton();
        jButtonCrear = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonCargar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jLabelImportar = new javax.swing.JLabel();
        jLabelCrear = new javax.swing.JLabel();
        jLabelBorrar = new javax.swing.JLabel();
        jLabelModificar = new javax.swing.JLabel();
        jLabelCargar = new javax.swing.JLabel();
        jLabelGuardar = new javax.swing.JLabel();
        jButtonConsultas = new javax.swing.JButton();
        jButtonEjercicios = new javax.swing.JButton();
        jLabelEjercicios = new javax.swing.JLabel();
        jLabelConsultas = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("NSimSun", 1, 48)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setText("ACADEMIA JAPÓN");

        jButtonImportar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonImportar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonImportar.setText("Importar");
        jButtonImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportarActionPerformed(evt);
            }
        });

        jButtonCrear.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCrear.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonCrear.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCrear.setText("Crear");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        jButtonModificar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonModificar.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonModificar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonBorrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBorrar.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonBorrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBorrar.setText("Borrar");

        jButtonCargar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCargar.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonCargar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCargar.setText("Cargar");

        jButtonGuardar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonGuardar.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonGuardar.setText("Guardar");

        jLabelImportar.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jLabelImportar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelImportar.setText("Importará datos desde la base de datos.");

        jLabelCrear.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jLabelCrear.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCrear.setText("Crearas datos manualmente o con datos.");

        jLabelBorrar.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jLabelBorrar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelBorrar.setText("Borraras datos.");

        jLabelModificar.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jLabelModificar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelModificar.setText("Modificaras datos.");

        jLabelCargar.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jLabelCargar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCargar.setText("Cargara datos desde archivos locales.");

        jLabelGuardar.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jLabelGuardar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelGuardar.setText("Guardará datos en archivos locales.");

        jButtonConsultas.setBackground(new java.awt.Color(255, 255, 255));
        jButtonConsultas.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonConsultas.setForeground(new java.awt.Color(0, 0, 0));
        jButtonConsultas.setText("Consultas");

        jButtonEjercicios.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEjercicios.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonEjercicios.setForeground(new java.awt.Color(0, 0, 0));
        jButtonEjercicios.setText("Ejercicios");

        jLabelEjercicios.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jLabelEjercicios.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEjercicios.setText("Ejercicios para BDD.");

        jLabelConsultas.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jLabelConsultas.setForeground(new java.awt.Color(0, 0, 0));
        jLabelConsultas.setText("Consulta los datos de la base de datos.");

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(456, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelTitulo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonImportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEjercicios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelImportar)
                            .addComponent(jLabelCrear)
                            .addComponent(jLabelBorrar)
                            .addComponent(jLabelModificar)
                            .addComponent(jLabelCargar)
                            .addComponent(jLabelGuardar)
                            .addComponent(jLabelEjercicios)
                            .addComponent(jLabelConsultas))
                        .addGap(8, 8, 8)))
                .addGap(523, 523, 523))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabelTitulo)
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonImportar)
                    .addComponent(jLabelImportar)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrear)
                    .addComponent(jLabelCrear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificar)
                    .addComponent(jLabelModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrar)
                    .addComponent(jLabelBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConsultas)
                    .addComponent(jLabelConsultas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEjercicios)
                    .addComponent(jLabelEjercicios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCargar)
                    .addComponent(jLabelCargar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGuardar)
                    .addComponent(jLabelGuardar))
                .addContainerGap(320, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportarActionPerformed
        bdImportada = true; // simulamos que ya se importó
        actualizarBotones(); // activamos los demás botones
    }//GEN-LAST:event_jButtonImportarActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        CrearAlumno crearAlumno = new CrearAlumno();
        crearAlumno.setVisible(true);
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        ModificarAlumno modificarAlumno= new ModificarAlumno();
        modificarAlumno.setVisible(true);
    }//GEN-LAST:event_jButtonModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PantallaPrincipal().setVisible(true);
        });
    }

    //Si
    private void actualizarBotones() {
        jButtonModificar.setEnabled(bdImportada);
        jButtonBorrar.setEnabled(bdImportada);
        jButtonConsultas.setEnabled(bdImportada);
        jButtonEjercicios.setEnabled(bdImportada);
    }

    //No

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonCargar;
    private javax.swing.JButton jButtonConsultas;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonEjercicios;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonImportar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelBorrar;
    private javax.swing.JLabel jLabelCargar;
    private javax.swing.JLabel jLabelConsultas;
    private javax.swing.JLabel jLabelCrear;
    private javax.swing.JLabel jLabelEjercicios;
    private javax.swing.JLabel jLabelGuardar;
    private javax.swing.JLabel jLabelImportar;
    private javax.swing.JLabel jLabelModificar;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration//GEN-END:variables
}
