/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import Control.EstadoAplicacion;
import java.awt.HeadlessException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rich
 */
public class Principal extends javax.swing.JFrame {

    EstadoAplicacion estado = new EstadoAplicacion();

    /**
     * Creates new form Principal
     */
    public Principal() {
        setTitle("Gestion de Centro Educativo");
        setSize(800, 500);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        initComponents();
        actualizarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButtonMadeBy = new javax.swing.JButton();
        jButtonCrearDatos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonBorrarDatos = new javax.swing.JButton();
        jButtonGuardarDatos = new javax.swing.JButton();
        jButtonCargar = new javax.swing.JButton();
        jButtonModificarDatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("NSimSun", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenido");
        jLabel2.setToolTipText("");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jButtonMadeBy.setBackground(new java.awt.Color(255, 255, 255));
        jButtonMadeBy.setFont(new java.awt.Font("NSimSun", 1, 14)); // NOI18N
        jButtonMadeBy.setForeground(new java.awt.Color(0, 0, 0));
        jButtonMadeBy.setText("Made by:");
        jButtonMadeBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMadeByActionPerformed(evt);
            }
        });

        jButtonCrearDatos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCrearDatos.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonCrearDatos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCrearDatos.setText("Crear Datos");
        jButtonCrearDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearDatosActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("NSimSun", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Elija una opcion:");
        jLabel3.setToolTipText("");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jButtonBorrarDatos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBorrarDatos.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonBorrarDatos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBorrarDatos.setText("Borrar Datos");
        jButtonBorrarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarDatosActionPerformed(evt);
            }
        });

        jButtonGuardarDatos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonGuardarDatos.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonGuardarDatos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonGuardarDatos.setText("Guardar Datos");
        jButtonGuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarDatosActionPerformed(evt);
            }
        });

        jButtonCargar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCargar.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonCargar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCargar.setText("Cargar Datos");
        jButtonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarActionPerformed(evt);
            }
        });

        jButtonModificarDatos.setBackground(new java.awt.Color(255, 255, 255));
        jButtonModificarDatos.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonModificarDatos.setForeground(new java.awt.Color(0, 0, 0));
        jButtonModificarDatos.setText("Modificar Datos");
        jButtonModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonMadeBy)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(819, 819, 819))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(jButtonCrearDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(jButtonGuardarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jButtonCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jButtonModificarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jButtonBorrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(404, 404, 404))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrearDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGuardarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModificarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBorrarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 364, Short.MAX_VALUE)
                .addComponent(jButtonMadeBy, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMadeByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMadeByActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMadeByActionPerformed

    private void jButtonCrearDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearDatosActionPerformed
        if (!estado.isBaseDeDatosCargada()) {
            JOptionPane.showMessageDialog(this,"No has cargado la base de datos, debera introducir los datos manualmente.");
        }
        PantallaCreacionManual pcm = new PantallaCreacionManual();
        pcm.setVisible(true);
    }//GEN-LAST:event_jButtonCrearDatosActionPerformed

    private void jButtonBorrarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarDatosActionPerformed
        if(!estado.isBaseDeDatosCargada()){
            JOptionPane.showMessageDialog(this, "Primero debes cargar la base de datos");
            return;
        }
        
        //borrar datos
    }//GEN-LAST:event_jButtonBorrarDatosActionPerformed

    private void jButtonGuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarDatosActionPerformed
        
    }//GEN-LAST:event_jButtonGuardarDatosActionPerformed

    private void jButtonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarActionPerformed
        try {
            //Consulta que cargue toda la base de datos
            estado.setBaseDeDatosCargada(true);
            actualizarBotones();

            JOptionPane.showMessageDialog(this, "Base de datos cargada correctamente");
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la base de datos");
        }
    }//GEN-LAST:event_jButtonCargarActionPerformed

    private void jButtonModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarDatosActionPerformed
        if (!estado.isBaseDeDatosCargada()) {
            JOptionPane.showMessageDialog(
                    this,"Primero debes cargar la base de datos.");
            return;
        }
        //Modificar los datos
    }//GEN-LAST:event_jButtonModificarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    private void actualizarBotones() {
        boolean bdCargada = estado.isBaseDeDatosCargada();

        jButtonCrearDatos.setEnabled(true);
        jButtonGuardarDatos.setEnabled(true);
        jButtonModificarDatos.setEnabled(bdCargada);
        jButtonBorrarDatos.setEnabled(bdCargada);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrarDatos;
    private javax.swing.JButton jButtonCargar;
    private javax.swing.JButton jButtonCrearDatos;
    private javax.swing.JButton jButtonGuardarDatos;
    private javax.swing.JButton jButtonMadeBy;
    private javax.swing.JButton jButtonModificarDatos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
