/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Concurrencia;

import Menus.MenuAlumno;
import menus.MenuCiclo;
import menus.MenuLineaMatricula;
import menus.MenuMatricula;
import menus.MenuModulo;
import javax.swing.JOptionPane;

/**
 * Formulario Swing para exportar los datos en sesión a distintos formatos de fichero
 * (CSV, TXT, JSON, Binario). Permite seleccionar la entidad a exportar mediante un JComboBox.
 * Tras escribir el fichero, sincroniza los mismos datos con la BD para garantizar
 * persistencia aunque el fichero se pierda.
 *
 * @author 1DAM
 */
public class Exportar extends javax.swing.JFrame {

    /**
     * Creates new form Guardar
     */
    public Exportar() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButtonTXT = new javax.swing.JButton();
        jButtonCSV = new javax.swing.JButton();
        jButtonBINARIO = new javax.swing.JButton();
        jButtonJSON = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("NSimSun", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("EXPORTAR DATOS");

        jButtonTXT.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTXT.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonTXT.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTXT.setText("TXT");
        jButtonTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTXTActionPerformed(evt);
            }
        });

        jButtonCSV.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCSV.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonCSV.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCSV.setText("CSV");
        jButtonCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSVActionPerformed(evt);
            }
        });

        jButtonBINARIO.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBINARIO.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonBINARIO.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBINARIO.setText("BINARIO");
        jButtonBINARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBINARIOActionPerformed(evt);
            }
        });

        jButtonJSON.setBackground(new java.awt.Color(255, 255, 255));
        jButtonJSON.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonJSON.setForeground(new java.awt.Color(0, 0, 0));
        jButtonJSON.setText("JSON");
        jButtonJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJSONActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODO", "ALUMNADO", "CICLOS", "MODULOS", "MATRICULAS", "LINEA MATRICULA" }));

        jLabel1.setText("Selecciona que quieres exportar: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButtonTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jButtonJSON, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jButtonBINARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(76, 76, 76)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(215, 215, 215)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTXT)
                    .addComponent(jButtonJSON)
                    .addComponent(jButtonBINARIO)
                    .addComponent(jButtonCSV))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJSONActionPerformed
        ejecutarExportacion((String) jComboBox1.getSelectedItem(), "JSON");
    }//GEN-LAST:event_jButtonJSONActionPerformed

    private void jButtonBINARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBINARIOActionPerformed
        ejecutarExportacion((String) jComboBox1.getSelectedItem(), "BINARIO");
    }//GEN-LAST:event_jButtonBINARIOActionPerformed

    private void jButtonCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSVActionPerformed
        ejecutarExportacion((String) jComboBox1.getSelectedItem(), "CSV");
    }//GEN-LAST:event_jButtonCSVActionPerformed

    private void jButtonTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTXTActionPerformed
        ejecutarExportacion((String) jComboBox1.getSelectedItem(), "TXT");
    }//GEN-LAST:event_jButtonTXTActionPerformed

    // =========================================================
    // =================== LÓGICA DE EXPORTACIÓN ===============
    // =========================================================

    private void ejecutarExportacion(String tabla, String formato) {
        try {
            if ("TODO".equals(tabla)) {
                int total = 0;
                for (String t : new String[]{"ALUMNADO", "CICLOS", "MODULOS", "MATRICULAS", "LINEA MATRICULA"}) {
                    total += exportarEntidad(t, formato);
                }
                JOptionPane.showMessageDialog(this,
                        "Exportación " + formato + " completada: " + total + " registros.");
            } else {
                int n = exportarEntidad(tabla, formato);
                JOptionPane.showMessageDialog(this,
                        "Exportación " + formato + " completada: " + n + " registros.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al exportar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private int exportarEntidad(String tabla, String formato) {
        return switch (tabla) {
            case "ALUMNADO"        -> MenuAlumno.exportar(formato);
            case "CICLOS"          -> MenuCiclo.exportar(formato);
            case "MODULOS"         -> MenuModulo.exportar(formato);
            case "MATRICULAS"      -> MenuMatricula.exportar(formato);
            case "LINEA MATRICULA" -> MenuLineaMatricula.exportar(formato);
            default -> throw new IllegalArgumentException("Tabla no reconocida: " + tabla);
        };
    }

    // =========================================================

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exportar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new Exportar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBINARIO;
    private javax.swing.JButton jButtonCSV;
    private javax.swing.JButton jButtonJSON;
    private javax.swing.JButton jButtonTXT;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
