/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas.Concurrencia;

import Menus.MenuAlumno;
import excepciones.YaImportadoException;
import java.util.HashSet;
import java.util.Set;
import menus.MenuCiclo;
import menus.MenuLineaMatricula;
import menus.MenuMatricula;
import menus.MenuModulo;

/**
 *
 * @author rich
 */
public class Importar extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Importar.class.getName());

    /**
     * Registra las combinaciones (tabla + formato) ya importadas en esta
     * sesión. Clave: "TABLA_FORMATO", p. ej. "ALUMNADO_TXT".
     */
    private final Set<String> yaImportados = new HashSet<>();

    /**
     * Creates new form Importar2
     */
    public Importar() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setText("Selecciona que quieres importar: ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCSV = new javax.swing.JButton();
        jButtonBINARIO = new javax.swing.JButton();
        jButtonJSON = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonTXT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCSV.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCSV.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonCSV.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCSV.setText("CSV");
        jButtonCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSVActionPerformed(evt);
            }
        });

        jButtonBINARIO.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBINARIO.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonBINARIO.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBINARIO.setText("BINARIO");
        jButtonBINARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBINARIOActionPerformed(evt);
            }
        });

        jButtonJSON.setBackground(new java.awt.Color(255, 255, 255));
        jButtonJSON.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonJSON.setForeground(new java.awt.Color(0, 0, 0));
        jButtonJSON.setText("JSON");
        jButtonJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJSONActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODO", "ALUMNADO", "CICLOS", "MODULOS", "MATRICULAS", "LINEA MATRICULA" }));

        jLabel1.setText("Selecciona que quieres importar: ");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("NSimSun", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("IMPORTAR DATOS");

        jButtonTXT.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTXT.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonTXT.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTXT.setText("TXT");
        jButtonTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTXTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(350, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(419, 419, 419))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(376, 376, 376))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButtonTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jButtonJSON, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jButtonBINARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(290, 290, 290))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(162, 162, 162)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTXT)
                    .addComponent(jButtonJSON)
                    .addComponent(jButtonBINARIO)
                    .addComponent(jButtonCSV))
                .addContainerGap(395, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSVActionPerformed
        ejecutarImportacion((String) jComboBox1.getSelectedItem(), "CSV");
    }//GEN-LAST:event_jButtonCSVActionPerformed

    private void jButtonBINARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBINARIOActionPerformed
        ejecutarImportacion((String) jComboBox1.getSelectedItem(), "BINARIO");
    }//GEN-LAST:event_jButtonBINARIOActionPerformed

    private void jButtonJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJSONActionPerformed
        ejecutarImportacion((String) jComboBox1.getSelectedItem(), "JSON");
    }//GEN-LAST:event_jButtonJSONActionPerformed

    private void jButtonTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTXTActionPerformed
        ejecutarImportacion((String) jComboBox1.getSelectedItem(), "TXT");
    }//GEN-LAST:event_jButtonTXTActionPerformed

    // =========================================================
    // =================== LÓGICA DE IMPORTACIÓN ===============
    // =========================================================

    /**
     * Punto de entrada desde los botones. Gestiona "TODO" y las tablas
     * individuales, comprueba duplicados y muestra el resultado al usuario.
     */
    private void ejecutarImportacion(String tabla, String formato) {
        try {
            if ("TODO".equals(tabla)) {
                // Orden respetando dependencias FK: ciclos → módulos → alumnos → matrículas → líneas
                String[] tablas = {"CICLOS", "MODULOS", "ALUMNADO", "MATRICULAS", "LINEA MATRICULA"};
                StringBuilder sb = new StringBuilder();
                StringBuilder errores = new StringBuilder();
                int total = 0;
                for (String t : tablas) {
                    String clave = t + "_" + formato;
                    try {
                        comprobarYaImportado(clave);
                        int n = procesarImportacion(t, formato);
                        if (n > 0) yaImportados.add(clave);
                        total += n;
                        sb.append(t).append(": ").append(n).append(" registros\n");
                    } catch (YaImportadoException e) {
                        sb.append(t).append(": ya importado (omitido)\n");
                    } catch (Exception e) {
                        errores.append(t).append(": ").append(e.getMessage()).append("\n");
                    }
                }
                String mensaje = "Importación completada:\n" + sb;
                if (errores.length() > 0) {
                    mensaje += "\nTablas con error (fichero no encontrado o formato incorrecto):\n" + errores;
                }
                boolean sinDatosNuevos = total == 0 && errores.length() == 0;
                javax.swing.JOptionPane.showMessageDialog(this, mensaje,
                        sinDatosNuevos ? "Sin datos nuevos" : errores.length() > 0 ? "Completado con advertencias" : "Éxito",
                        sinDatosNuevos ? javax.swing.JOptionPane.WARNING_MESSAGE : errores.length() > 0 ? javax.swing.JOptionPane.WARNING_MESSAGE : javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                String clave = tabla + "_" + formato;
                comprobarYaImportado(clave);
                int n = procesarImportacion(tabla, formato);
                if (n > 0) yaImportados.add(clave);
                if (n == 0) {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "No hay datos nuevos que importar en " + tabla + " (" + formato + ").\nTodos los registros ya existen en la base de datos.",
                            "Sin datos nuevos", javax.swing.JOptionPane.WARNING_MESSAGE);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Importados " + n + " registros de " + tabla + " (" + formato + ")",
                            "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (YaImportadoException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    e.getMessage(), "Ya importado", javax.swing.JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al importar: " + e.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Comprueba si la combinación tabla+formato ya fue importada en esta sesión.
     *
     * @param clave Identificador único "TABLA_FORMATO"
     * @throws YaImportadoException si ya fue importado anteriormente
     */
    private void comprobarYaImportado(String clave) throws YaImportadoException {
        if (yaImportados.contains(clave)) {
            throw new YaImportadoException(
                    """
                    Ya se importo esta tabla en el formato indicado durante esta sesion.
                    Reinicia la aplicacion para volver a importar.""");
        }
    }

    /**
     * Despacha la importación al método concreto según tabla y formato.
     *
     * @param tabla   Nombre de la tabla seleccionada en el combo
     * @param formato Formato del fichero
     * @return Número de registros importados correctamente
     * @throws Exception si hay error en lectura o inserción
     */
    private int procesarImportacion(String tabla, String formato) throws Exception {
        return switch (tabla) {
            case "ALUMNADO"        -> MenuAlumno.importar(formato);
            case "CICLOS"          -> MenuCiclo.importar(formato);
            case "MODULOS"         -> MenuModulo.importar(formato);
            case "MATRICULAS"      -> MenuMatricula.importar(formato);
            case "LINEA MATRICULA" -> MenuLineaMatricula.importar(formato);
            default -> throw new Exception("Tabla no reconocida: " + tabla);
        };
    }

    // =========================================================

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new Importar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBINARIO;
    private javax.swing.JButton jButtonCSV;
    private javax.swing.JButton jButtonJSON;
    private javax.swing.JButton jButtonTXT;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
