package pantallas.Concurrencia;

import Menus.MenuAlumno;
import Menus.MenuCiclo;
import Menus.MenuLineaMatricula;
import Menus.MenuMatricula;
import Menus.MenuModulo;
import javax.swing.JOptionPane;

public class Importar extends javax.swing.JFrame {
    

    /**
     * Creates new form Importar
     */
    public Importar() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        configurarOtro();
    }

    private void configurarOtro() {
        jTextField1.setEnabled(false);
        jTextField1.setToolTipText("Ruta del fichero con extensión (ej: /home/usuario/alumno.csv)");

        javax.swing.JCheckBox checkOtro = new javax.swing.JCheckBox("Otro (ruta personalizada)");
        checkOtro.addItemListener(e -> {
            boolean activo = checkOtro.isSelected();
            jTextField1.setEnabled(activo);
            if (!activo) jTextField1.setText("");
        });

        javax.swing.JPanel panelExtra = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        panelExtra.add(checkOtro);

        javax.swing.JPanel wrapper = new javax.swing.JPanel(new java.awt.BorderLayout());
        wrapper.add(getContentPane(), java.awt.BorderLayout.CENTER);
        wrapper.add(panelExtra, java.awt.BorderLayout.SOUTH);

        setContentPane(wrapper);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButtonTXT = new javax.swing.JButton();
        jButtonCSV = new javax.swing.JButton();
        jButtonBINARIO = new javax.swing.JButton();
        jButtonJSON = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("NSimSun", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("IMPORTAR DATOS");

        jButtonTXT.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTXT.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonTXT.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTXT.setText("TXT");
        jButtonTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTXTActionPerformed(evt);
            }
        });

        jButtonCSV.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCSV.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonCSV.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCSV.setText("CSV");
        jButtonCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCSVActionPerformed(evt);
            }
        });

        jButtonBINARIO.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBINARIO.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonBINARIO.setForeground(new java.awt.Color(0, 0, 0));
        jButtonBINARIO.setText("BINARIO");
        jButtonBINARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBINARIOActionPerformed(evt);
            }
        });

        jButtonJSON.setBackground(new java.awt.Color(255, 255, 255));
        jButtonJSON.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jButtonJSON.setForeground(new java.awt.Color(0, 0, 0));
        jButtonJSON.setText("JSON");
        jButtonJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJSONActionPerformed(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODO", "ALUMNADO", "CICLOS", "MODULOS", "MATRICULAS", "LINEA MATRICULA" }));

        jLabel1.setText("Selecciona que quieres importar: ");

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jButtonTXT, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jButtonJSON, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jButtonBINARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(119, 119, 119)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTXT)
                    .addComponent(jButtonJSON)
                    .addComponent(jButtonBINARIO)
                    .addComponent(jButtonCSV))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTXTActionPerformed
        ejecutarImportacion((String) jComboBox1.getSelectedItem(), "TXT");
    }//GEN-LAST:event_jButtonTXTActionPerformed

    private void jButtonCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCSVActionPerformed
        ejecutarImportacion((String) jComboBox1.getSelectedItem(), "CSV");
    }//GEN-LAST:event_jButtonCSVActionPerformed

    private void jButtonBINARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBINARIOActionPerformed
        ejecutarImportacion((String) jComboBox1.getSelectedItem(), "BINARIO");
    }//GEN-LAST:event_jButtonBINARIOActionPerformed

    private void jButtonJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJSONActionPerformed
        ejecutarImportacion((String) jComboBox1.getSelectedItem(), "JSON");
    }//GEN-LAST:event_jButtonJSONActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // vacío: el usuario pulsa Enter en el campo de ruta, no hace falta acción
    }//GEN-LAST:event_jTextField1ActionPerformed

    // -------------------------------------------------------------------------
    // Lógica de importación
    // -------------------------------------------------------------------------

    private void ejecutarImportacion(String entidad, String formato) {
        String ruta = jTextField1.getText().trim();

        if (jTextField1.isEnabled()) {
            // Modo Otro: la ruta manda, el formato se detecta por extensión
            if (ruta.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Debes introducir la ruta del fichero.",
                        "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if ("TODO".equals(entidad)) {
                JOptionPane.showMessageDialog(this,
                        "No se puede usar ruta personalizada con la opción TODO.\nSelecciona una entidad concreta.",
                        "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }
            formato = detectarFormatoPorExtension(ruta);
            if (formato == null) {
                JOptionPane.showMessageDialog(this,
                        "No se reconoce el formato del fichero.\nUsa extensión .csv, .txt, .json o .dat",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } else {
            ruta = null; // usa la ruta por defecto de Config
        }

        try {
            int total = importarEntidad(entidad, formato, ruta != null ? quitarExtension(ruta) : null);

            if (total == 0) {
                JOptionPane.showMessageDialog(this,
                        "No hay nueva información.",
                        "Importación", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Importados " + total + " registros correctamente.",
                        "Importación completada", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al importar:\n" + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private String detectarFormatoPorExtension(String ruta) {
        if (ruta.endsWith(".csv"))  return "CSV";
        if (ruta.endsWith(".txt"))  return "TXT";
        if (ruta.endsWith(".json")) return "JSON";
        if (ruta.endsWith(".dat"))  return "BINARIO";
        return null;
    }

    private String quitarExtension(String ruta) {
        int posicion = ruta.lastIndexOf('.');
        return posicion > 0 ? ruta.substring(0, posicion) : ruta;
    }

    private int importarEntidad(String entidad, String formato, String rutaBase) throws Exception {
        if ("TODO".equals(entidad)) {
            return importarTodo(formato);
        }
        return importarUna(entidad, formato, rutaBase);
    }

    private int importarTodo(String formato) throws Exception {
        int total = 0;
        total += MenuCiclo.importar(formato);
        total += MenuModulo.importar(formato);
        total += MenuAlumno.importar(formato);
        total += MenuMatricula.importar(formato);
        total += MenuLineaMatricula.importar(formato);
        return total;
    }

    private int importarUna(String entidad, String formato, String rutaBase) throws Exception {
        if (rutaBase != null) {
            return switch (entidad) {
                case "ALUMNADO"        -> MenuAlumno.importar(formato, rutaBase);
                case "CICLOS"          -> MenuCiclo.importar(formato, rutaBase);
                case "MODULOS"         -> MenuModulo.importar(formato, rutaBase);
                case "MATRICULAS"      -> MenuMatricula.importar(formato, rutaBase);
                case "LINEA MATRICULA" -> MenuLineaMatricula.importar(formato, rutaBase);
                default -> throw new Exception("Entidad no reconocida: " + entidad);
            };
        }
        return switch (entidad) {
            case "ALUMNADO"        -> MenuAlumno.importar(formato);
            case "CICLOS"          -> MenuCiclo.importar(formato);
            case "MODULOS"         -> MenuModulo.importar(formato);
            case "MATRICULAS"      -> MenuMatricula.importar(formato);
            case "LINEA MATRICULA" -> MenuLineaMatricula.importar(formato);
            default -> throw new Exception("Entidad no reconocida: " + entidad);
        };
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Importar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Importar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBINARIO;
    private javax.swing.JButton jButtonCSV;
    private javax.swing.JButton jButtonJSON;
    private javax.swing.JButton jButtonTXT;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
